### PR TITLE
libopenjp2: Fix static build on Windows

### PR DESCRIPTION
**Pull request by xclaesse**
Applications that build static libopenjp2 needs OPJ_STATIC define when
including its header.

### CODE REVIEW

**Comment by xclaesse** [comment]
@fasterthanlime I saw you did similar in other projects (e.g. https://github.com/frida/proxy-libintl/pull/2). Seems we have to do that trick pretty much in all wraps...

**Comment by eli-schwartz** [comment]
That's probably also relevant to pkg-config.

**Comment by xclaesse** [comment]
@eli-schwartz Hm good point. I've never seen a pkg config file doing that, but we could start that trend I guess... Not that this is only relevant to static build for Windows. At least glib define that in their public headers so it's not needed for that lib. Not sure how common that is.

**Comment by eli-schwartz** [comment]
> I've never seen a pkg config file doing that, but we could start that trend I guess...

Any pkg-config file which intends to support Windows would need to do that. There are definitely pkg-config files that in fact do so.

I know I've seen it, I just forget where... they probably aren't in the linux generated versions of the .pc files so I cannot trivially find them. :p

**Comment by xclaesse** [comment]
@eli-schwartz done, and did the same for libxml2: https://github.com/mesonbuild/wrapdb/pull/354

**Comment by xclaesse** [comment]
Since the same fix got approved in other wraps, let's just merge it now.

**Pull request merged**
