### PR TITLE
rdkafka: update to 1.8.2

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
```

lz4| Project name: lz4
lz4| Project version: 1.9.3
lz4| C compiler for the host machine: cl (msvc 19.31.31105 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31105 for x64")
lz4| C linker for the host machine: link link 14.31.31105.0
lz4| Program GetLz4LibraryVersion.py found: YES (C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe D:\a\wrapdb\wrapdb\subprojects\lz4-1.9.3\contrib/meson/meson\GetLz4LibraryVersion.py)
lz4| WARNING: You should add the boolean check kwarg to the run_command call.
lz4| It currently defaults to false,
lz4| but it will default to true in future releases of meson.
lz4| See also: https://github.com/mesonbuild/meson/issues/9300

subprojects\lz4-1.9.3\contrib\meson\meson\meson.build:31:0: ERROR: Fatal warnings enabled, aborting
```

Can't edit meson.build as the source is not in tree.

@eli-schwartz any suggestions?

**Comment by neheb** [comment]
```
subprojects/openssl-3.0.2/meson.build:16:2: ERROR: Command "/Users/runner/work/wrapdb/wrapdb/subprojects/openssl-3.0.2/generator.sh" failed with status 2.
```

sounds like the OpenSSL wrap needs fixing.

**Comment by eli-schwartz** [comment]
The lz4 issue is fixed by https://github.com/lz4/lz4/pull/1049, unfortunately the latest release was in November 2020.

**Comment by neheb** [comment]
```
lz4| Project name: lz4
lz4| Project version: 1.9.3
lz4| C compiler for the host machine: cl (msvc 19.31.31105 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31105 for x64")
lz4| C linker for the host machine: link link 14.31.31105.0
lz4| Program GetLz4LibraryVersion.py found: YES (C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe D:\a\wrapdb\wrapdb\subprojects\lz4-1.9.3\contrib/meson/meson\GetLz4LibraryVersion.py)
lz4| WARNING: You should add the boolean check kwarg to the run_command call.
lz4| It currently defaults to false,
lz4| but it will default to true in future releases of meson.
lz4| See also: https://github.com/mesonbuild/meson/issues/9300

subprojects\lz4-1.9.3\contrib\meson\meson\meson.build:31:0: ERROR: Fatal warnings enabled, aborting

A full log can be found at D:\a\wrapdb\wrapdb\_build\meson-logs\meson-log.txt
==== meson-log.txt ====
  File "D:\a\wrapdb\wrapdb\tools\sanity_checks.py", line 180, in test_releases
    self.check_new_release(name)
  File "D:\a\wrapdb\wrapdb\tools\sanity_checks.py", line 258, in check_new_release
    subprocess.check_call(['meson', 'setup', builddir] + options)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', 'setup', '_build', '-Dpython.install_env=auto', '-Dwraps=rdkafka', '--fatal-meson-warnings', '-Dpkg_config_path=/usr/local/opt/openssl@1.1/lib/pkgconfig', '-Drdkafka:WITH_SASL=disabled', '-Drdkafka:WITH_ZSTD=disabled']' returned non-zero exit status 1.
```

how to proceed here? Disable fatal warnings?

**Comment by neheb** [comment]
Fixed.

**Pull request merged**
