### PR TITLE
Update libuv to 1.48.0

### PR DESCRIPTION
**Pull request by ibc**
### Details

- libuv 1.48.0 release notes: https://github.com/libuv/libuv/releases/tag/v1.48.0
- Diff between 1.47.0 and 1.48.0: https://github.com/libuv/libuv/compare/v1.47.0...v1.48.0

### TODO

The `CMakeLists.txt` file in libuv 1.48.0 comes with some changes that I do not how to translate to `meson.build`:

```cmake
if (MSVC)
  # Error on calling undeclared functions.
  list(APPEND uv_cflags "/we4013")
endif()
```

```cmake
if(WIN32)
  add_custom_command(TARGET uv_run_tests POST_BUILD
                     COMMAND "${CMAKE_COMMAND}" -E copy
                     "$<TARGET_FILE:uv_run_tests>"
                     "$<TARGET_FILE_DIR:uv_run_tests>/uv_run_tests_no_ext")
endif()
```

```cmake
if(WIN32)
  add_custom_command(TARGET uv_run_tests_a POST_BUILD
                       COMMAND "${CMAKE_COMMAND}" -E copy
                       "$<TARGET_FILE:uv_run_tests_a>"
                       "$<TARGET_FILE_DIR:uv_run_tests_a>/uv_run_tests_a_no_ext")
endif()
```

```cmake
if(WIN32)
  add_custom_command(TARGET uv_run_tests POST_BUILD
                     COMMAND "${CMAKE_COMMAND}" -E copy
                     "$<TARGET_FILE:uv_run_tests>"
                     "$<TARGET_FILE_DIR:uv_run_tests>/uv_run_tests_no_ext")
endif()
```

```cmake
get_filename_component(CMAKE_C_COMPILER_DIR ${CMAKE_C_COMPILER} DIRECTORY)
if(ASAN)
  file(INSTALL "${CMAKE_C_COMPILER_DIR}/llvm-symbolizer.exe" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
  file(INSTALL "${CMAKE_C_COMPILER_DIR}/clang_rt.asan_dynamic-x86_64.dll" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
  file(INSTALL "${CMAKE_C_COMPILER_DIR}/clang_rt.asan_dbg_dynamic-x86_64.dll" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
endif()
```

I assume that the first one is not really needed here, next ones are not important since they only affect tests, and the last one is about ASAN so I don't think it's relevant here.

### CODE REVIEW

**Comment by ibc** [comment]
It looks like this is not good yet:

https://github.com/mesonbuild/wrapdb/actions/runs/8100266673/job/22138007337?pr=1430

**Comment by nazar-pc** [comment]
```
if (MSVC)
  # Error on calling undeclared functions.
  list(APPEND uv_cflags "/we4013")
endif()
```
This clearly appends a C compiler flag for MSVC.

`copy` stuff seems to be copying files into name with no `.exe` extension, I guess it makes some stuff easier elsewhere.

ASAN is probably not relevant.

**Comment by ibc** [comment]
> This clearly appends a C compiler flag for MSVC.

Problem is that I don't know where/how to set that flag for MSVC. There are other flags in the CMakeLists file that are added using different calls.

> copy stuff seems to be copying files into name with no .exe extension, I guess it makes some stuff easier elsewhere.

I couldn't find any code in meson.build to do the same. I'll try more.

**Comment by nazar-pc** [comment]
> Problem is that I don't know where/how to set that flag for MSVC

See `libuv_cargs` in `meson.build` you're editing :slightly_smiling_face: 

> I couldn't find any code in meson.build to do the same. I'll try more.

I'm not sure it is relevant for Meson.

**Comment by ibc** [comment]
> See `libuv_cargs` in `meson.build` you're editing 🙂

Yes, and I added it locally and removed it before pushing it since in CMakeLists.txt they add that flag this way:

```
list(APPEND uv_cflags "/we4013")
```

While other flags are added this way:

```
check_c_compiler_flag(/wd4100 UV_LINT_NO_UNUSED_PARAMETER_MSVC)
// many more
```

I don't think those do the same, or perhaps yes. I'll try.

**Comment by ibc** [comment]
It looks that I need an approval to run CI again after my latest commit. @neheb or someone else, could you please make it possible?

**Comment by ibc** [comment]
Hi, maintainers. I would need another approval to run CI after pushing a fix :) Thanks.

**Comment by nazar-pc** [comment]
> It looks that I need an approval to run CI again after my latest commit. @neheb or someone else, could you please make it possible?

It is just GitHub Actions, push experiments into your private branch, run CI there and once everything is green push it in a nice squashed way upstream. No need for pinging on every attempt.

**Comment by ibc** [comment]
> It is just GitHub Actions, push experiments into your private branch, run CI there and once everything is green push it in a nice squashed way upstream. No need for pinging on every attempt.

Oh, of course. Thanks. On it: https://github.com/ibc/wrapdb/actions

**Comment by ibc** [comment]
> > It is just GitHub Actions, push experiments into your private branch, run CI there and once everything is green push it in a nice squashed way upstream. No need for pinging on every attempt.
> 
> Oh, of course. Thanks. On it: https://github.com/ibc/wrapdb/actions

Wow, it's running CI for ALL projects hosted in wrapdb: https://github.com/ibc/wrapdb/actions/runs/8109920706/job/22166101033
It can take long hours...

However the action running in this PR just tested libuv:
https://github.com/mesonbuild/wrapdb/actions/runs/8108790394/job/22163146326?pr=1430

**Comment by ibc** [comment]
CI is failing in **my branch** in ALL OS machines due to this error that I do not understand:

```
2024-03-01T12:06:26.2398777Z ======================================================================
2024-03-01T12:06:26.2399104Z FAIL: test_releases (__main__.TestReleases) (step='version is tagged', name='libuv')
2024-03-01T12:06:26.2399364Z ----------------------------------------------------------------------
2024-03-01T12:06:26.2399468Z Traceback (most recent call last):
2024-03-01T12:06:26.2399800Z   File "/home/runner/work/wrapdb/wrapdb/./tools/sanity_checks.py", line 250, in test_releases
2024-03-01T12:06:26.2399897Z     self.assertIn(t, self.tags)
2024-03-01T12:06:26.2400077Z AssertionError: 'libuv_1.42.0-1' not found in []
```

May I get some help, please? https://github.com/ibc/wrapdb/actions/runs/8109920706/job/22166101033

**Comment by ibc** [comment]
In `sanity_checks.py`:

```py
stdout = subprocess.check_output(['git', 'tag'])
        cls.tags = [t.strip() for t in stdout.decode().splitlines()]
```

So it fails because my fork only has `master` branch and has no git tags copied from mainstream project.

**Comment by ibc** [comment]
Closing this PR in favour of https://github.com/mesonbuild/wrapdb/pull/1432 which is the same but the fork contains all the branches and tags in mainstream so CI won't fail due to that.

**Pull request closed without merging**
