### PR TITLE
cpr: bump to 1.7.2

### PR DESCRIPTION
**Pull request by sielicki**
Signed-off-by: Nicky Sielicki <sielicki@yandex.com>

### CODE REVIEW

**Comment by sielicki** [comment]
I just did the bump without `_dep` updates, do you need me to do that as well?

**Comment by eli-schwartz** [comment]
Yes, please add it to the same PR.

**Comment by sielicki** [comment]
Should be better now.

**Comment by eli-schwartz** [comment]
You can install curl in the linux CI via `ci_config.json`. Will be harder on Windows...

**Comment by sielicki** [comment]
Do you mind if we just leave it disabled for now?

**Comment by sielicki** [comment]
Running the checks works locally for me, not sure what's going on here.

**Comment by eli-schwartz** [comment]
Did you try installing the curl development package via `debian_packages` in the ci_config.json file? :)

**Comment by neheb** [comment]
Please rebase.

**Comment by neheb** [comment]
Remove entries from ci_config

**Comment by neheb** [comment]
ci_config.json has not bee changed.

You also need to add

```
  "cpr": {
    "debian_packages": [
      "libcurl4-gnutls-dev",
    ],
    "_comment": ["curl not available with MSVC CI"],
    "build_on": {
      "windows": false
    },
    "build_options": [
      "cpp_std=c++14"
    ]
  },
```

**Comment by sielicki** [comment]
This has stalled twice now in review where I don't know enough about your the CI to attempt to fix it. I just wanted to bump the numbers and the hash, and change the filenames that upstream is using. Can you take this over? Sorry.

**Comment by neheb** [comment]
Succeeded by https://github.com/mesonbuild/wrapdb/pull/422

**Pull request closed without merging**
