### PR TITLE
try fixing macOS CI

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Since clearly the macOS runners were NOT fixed, because you had to use the github actions python instead of the homebrew one which "fixes a relinking issue" by... not using the homebrew python...

I don't understand what this "fixed" about the macOS CI?

**Comment by neheb** [comment]
Example broken run: https://pipelines.actions.githubusercontent.com/serviceHosts/41920d4f-a01c-4531-8a4e-8f68e9dab867/_apis/pipelines/1/runs/4285/signedlogcontent/4?urlExpires=2022-12-18T00%3A23%3A10.8126774Z&urlSigningMethod=HMACV1&urlSignature=sou1W%2Fmqxq9vGP43RfTXzRVpEibe%2Fl5SUAXIql1aOJ8%3D

All of them were like this.

**Comment by eli-schwartz** [comment]
I don't know what that link goes to, it's a temporary link that expires in under a minute.

**Comment by neheb** [comment]
https://github.com/mesonbuild/wrapdb/actions/runs/3717524367

**Pull request merged**
