### PR TITLE
abseil-cpp: update to 20230125.2

### PR DESCRIPTION
**Pull request by v1993**

### CODE REVIEW

**Comment by neheb** [comment]
Needs more work than a simple version bump. I’m trying to update protobuf but this package needs fixing first.

**Comment by v1993** [comment]
It looks like (upstream) changes from previous version are trivial, though?

**Comment by neheb** [comment]
https://github.com/mesonbuild/wrapdb/pull/932 was incomplete is what I'm saying

**Comment by v1993** [comment]
Makes sense. Sadly, I don't have a program at hand to test that it links/works right now. Nice that upstream has tests, though.

**Comment by neheb** [comment]
My WIP branch for protobuf 3.22 was not pushed to github unfortunately. I won't be home for 2 months.

**Comment by neheb** [comment]
@v1993 see https://github.com/neheb/wrapdb/tree/3

**Comment by v1993** [comment]
@neheb Should I just close this, then?

**Comment by neheb** [comment]
nah just rebase

**Comment by inglor** [comment]
The current absl-wrap is not properly linking as others pointed out and I mentioned on my last PR (after merging). I didn't have time to look at it then and doubt I will have any time soon, but I can test with a program if we got a new version the wrap.

**Comment by bgilbert** [comment]
Obsoleted by #1180 and #1624.

**Pull request closed without merging**
