### PR TITLE
add libkqueue

### PR DESCRIPTION
**Pull request by Jan200101**
a wrap for the libkqueue library

It supports Windows, Linux and SunOS out of the box and is based on the official CMakeLists.txt

Darwin/MacOS builds are disabled since it inherited kqueue from FreeBSD and thus does not need this library

### CODE REVIEW

**Comment by Jan200101** [comment]
Windows errors, fun

**Comment by Jan200101** [comment]
Some MSVC specific errors.
I'll ask upstream if MSVC is supported or not and fix them if it is

**Comment by eli-schwartz** [comment]
According to https://github.com/mheily/libkqueue/issues/128 the status is "we didn't explicitly try it, but if it doesn't work then patches welcome".

**Comment by Jan200101** [comment]
will work on patches

**Comment by Jan200101** [comment]
the meson build works when adopting the changes from https://github.com/mheily/libkqueue/pull/131.

I'll convert this to a draft and wait for the next release

**Comment by neheb** [comment]
New release is out.

**Comment by Jan200101** [comment]
Fighting the Visual Studio CI on every step, this PR is finally ready

**Comment by neheb** [comment]
On musl this fails to compile:

```
ninja: job failed: cc -Isubprojects/libkqueue-2.6.1/libkqueue.so.p -Isubprojects/libkqueue-2.6.1 -I../../home/mangix/devstuff/wrapdb/subprojects/libkqueue-2.
In file included from ^[[01m^[[K../../home/mangix/devstuff/wrapdb/subprojects/libkqueue-2.6.1/src/common/debug.c:21^[[m^[[K:                                 ^[[01m^[[K../../home/mangix/devstuff/wrapdb/subprojects/libkqueue-2.6.1/src/common/debug.h:93:5:^[[m^[[K ^[[01;31m^[[Kerror: ^[[m^[[Kunknown type name '^[[01   93 |     ^[[01;31m^[[Kpthread_mutex_t^[[m^[[K mtx_lock;                                                                                                         |     ^[[01;31m^[[K^~~~~~~~~~~~~~~^[[m^[[K
```

unknown type name pthread_mutex_t

**Pull request merged**
