### PR TITLE
Add oatpp-sqlite

### PR DESCRIPTION
**Pull request by Totto16**
Add oatpp-sqlite
The repo can be found [here](https://github.com/oatpp/oatpp-sqlite)

### CODE REVIEW

**Comment by Totto16** [comment]
I found an error in the base module 'oatpp' (only on windows, when you use it as dependency) so this can only be merged after #1039 is merged

**Comment by Totto16** [comment]
After some investigating, the same errors from 'oatpp' (See #1031) occurs on windows, they are remainigs from that module, but fixed already in upstream, but no new release has been made yet. So disabling the tests in windows, as long as the version is to be known to have bugs is the best solution, as also discussed in the PR above discussed.

**Comment by Totto16** [comment]
This is now ready and squashed

**Comment by Totto16** [comment]
@neheb LOL is this supposed to happen:
image

**Comment by neheb** [comment]
nope. I'm guessing some race condition.

**Comment by Totto16** [comment]
Interesting :joy:

**Pull request merged**
