### PR TITLE
vulkan-headers: update to 1.2.203

### PR DESCRIPTION
**Pull request by neheb**
Fixed actual usage by adding a provide line.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Vulkan-Headers upstream doesn't provide a pkg-config file or a cmake file or an anything. How does this provide section fit into expected usage? People cannot do `dependency('vulkan-headers')` because it cannot be satisfied except via fallback... what should they do instead?

**Comment by neheb** [comment]
If dependency cannot be used, how is this meant to be used?

**Comment by eli-schwartz** [comment]
I don't know!

What I'd like to know is how the upstream Khronos Group expects people to consume this. Let's say it is installed as a system dependency, how do projects detect *that*?

**Comment by neheb** [comment]
removed provides line.

**Pull request merged**
