### PR TITLE
Add oatpp-swagger

### PR DESCRIPTION
**Pull request by Totto16**
Add oatpp-swagger
The repo can be found [here](https://github.com/oatpp/oatpp-swagger)

This depends on #1039 and can only be merged after that!

### CODE REVIEW

**Comment by jpakkane** [comment]
⚔️ conflicts.

**Comment by Totto16** [comment]
> crossed_swords conflicts.

as stated, it depends on #1031, but atm github is down for me, I can't push anything, it's stabilizing now (I hope)

**Comment by jpakkane** [comment]
Squash this down to one commit when it is ready.

**Comment by Totto16** [comment]
It is now squashed

**Pull request merged**
