### PR TITLE
wayland-protocols: update to 1.32

### PR DESCRIPTION
**Pull request by dcbaker**

### CODE REVIEW

**Comment by neheb** [comment]
Didn’t this get macOS support?

**Comment by dcbaker** [comment]
The protocols themselves might build okay on Windows or MacOS, but the tests require wayland-scanner, which only works on DRM based kernels (Linux, *BSD, Solaris) by design.

**Comment by neheb** [comment]
I remember a wayland project gaining macOS(kthread) support. Maybe libwayland or something.

**Comment by dcbaker** [comment]
It might in the newer wayland 1.22 release, but we need new wayland protocols to build that.

**Comment by dcbaker** [comment]
Apparently yes, 1.22 does work on macos.

**Comment by neheb** [comment]
So I guess upstream needs to fix protocols as well.

**Comment by dcbaker** [comment]
I think this is a check and egg problem, but lets see what happens. I've added an update for wayland to 1.22 (https://github.com/mesonbuild/wrapdb/pull/1134), and then rebased this on that. Let's see what happens here.

**Comment by dcbaker** [comment]
Nope, more reading. There's a port of wayland to MacOS, but it doesnt look like it was ever upstreamed.

**Comment by dcbaker** [comment]
So I'm not sure what to do here. It seems a little odd to ask upstream to add "unsupported platform" errors just for our CI, but?

**Pull request merged**
