### PR TITLE
minizip-ng: add

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by eli-schwartz** [comment]
No.

Minizip is part of zlib, feel free to update that to provide the "minizip" dependency. Zlib-ng isn't API/ABI compatible and upstream acknowledges this by making it provide "libminizip-ng.so" and 'minizip-ng.pc"

**Comment by neheb** [comment]
sure. that's why there's a compatibility switch.

**Comment by eli-schwartz** [comment]
I don't want a compatibility switch.

I want incompatible software to stop offering the ability to break stuff, but I can't make zlib-ng do anything they don't want to do. As far as the WrapDB is concerned, I want incompatible software to not list "minizip" in its provides section when it doesn't.

**Comment by neheb** [comment]
works for domoticz.

anyway, I'll rework to remove it.

**Comment by neheb** [comment]
```
 Installing subprojects\minizip-ng-3.0.6\minizip-ng.dll to D:\a\wrapdb\wrapdb\_build\pkg\bin

ERROR: File 'subprojects\\minizip-ng-3.0.6\\minizip-ng.lib' could not be found
```

is this a bug? the change here is the name from minizip to minizip-ng.

**Comment by neheb** [comment]
```
No tests defined.
s.
======================================================================
ERROR: test_releases (__main__.TestReleases) (step='check_new_release', name='minizip-ng')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\wrapdb\wrapdb\tools\sanity_checks.py", line 204, in test_releases
    self.check_new_release(name)
  File "D:\a\wrapdb\wrapdb\tools\sanity_checks.py", line 298, in check_new_release
    subprocess.check_call(['meson', 'install', '-C', builddir, '--destdir', 'pkg'])
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', 'install', '-C', '_build', '--destdir', 'pkg']' returned non-zero exit status 1.
```

I'm all ears.

**Comment by neheb** [comment]
I see the issue. Upstream exports nothing without compat enabled. I don't feel like working around this.

**Comment by neheb** [comment]
According to https://github.com/zlib-ng/minizip-ng/issues/475 , upstream relies on CMake's EXPORT_ALL_SYMBOLS

**Comment by neheb** [comment]
alright this is ready.

**Pull request merged**
