### PR TITLE
Add new wrap for TartanLlama/expected

### PR DESCRIPTION
**Pull request by punytroll**
- header only library
- without tests

### CODE REVIEW

**Comment by jpakkane** [comment]
The [corresponding optional library] is called `tl-optional` in WrapDB, so this should be called `tl-expected` for consistency.

**Comment by jpakkane** [comment]
I can squash this now, but in the future please keep MRs to a single commit.. Thanks.

**Comment by punytroll** [comment]
Thanks for the squash merge.

I saw, that other pull requests always force-pushed their changes resulting in one commit only but I am not familiar with the workflow. Could you please give me a pointer? Tanks!

**Comment by jpakkane** [comment]
Basically you do your changes and then:

    git commit -a --amend

and then

    git push --force

**Pull request merged**
