### PR TITLE
github: add dependabot

### PR DESCRIPTION
**Pull request by neheb**
Bot to update CI.

This will update at least actions/checkout on merge.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
There's nothing to do here, it accomplishes zero things of value. I also generally object to dependabot because it's absolutely horrible around batching PRs.

If we were to use anything it should be renovate-bot, which is well behaved in large part because it is also open source. But I don't really think we should do anything.

**Comment by neheb** [comment]
```
git grep uses: | cut -d ':' -f 3 | sort
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 actions/checkout@v3
 ilammy/msvc-dev-cmd@v1
 ilammy/msvc-dev-cmd@v1
 ilammy/msvc-dev-cmd@v1
 ilammy/msvc-dev-cmd@v1
 msys2/setup-msys2@v2
 msys2/setup-msys2@v2
```
are subject to update.

**Comment by eli-schwartz** [comment]
My understanding is that the only thing that major version updates for actions/checkout actually changes is the internal nodejs version, which is the biggest fattest nothingburger ever. The previous major release is still fully supported with the same new features because there's rarely ever breaking changes, GitHub just considers the internal nodejs version to be a breaking change because GitHub Enterprise customers would need to update their deployment to new Actions runners.

**Comment by neheb** [comment]
Meh. Guess I'll manually do it.

**Comment by eli-schwartz** [comment]
My question isn't about whether there are things "subject to update", but rather "are there ever updates of substance".

What are we updating manually other than a nodejs internal version?

**Comment by neheb** [comment]
@eli-schwartz reworked PR. Please review.

**Pull request merged**
