### PR TITLE
dlfcn-win32: add

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
```
subprojects/libarchive-3.6.2/meson.build:396:8: ERROR: Dependencies must be external dependencies
```

Of course...

**Comment by neheb** [comment]
this dl.h is suspicious.

**Comment by jpakkane** [comment]
This adds a dependency called `dl` but there is currently no way to say that it only works on Windows. Which is to say it might get downloaded and built on unixy platforms. Which leads to build failures. Dunno if we should guard against it somehow or whether we ignore this as too rare a case.

**Comment by neheb** [comment]
OTOH most usages of dependency('dl') here have required: false or are a feature option.

**Pull request merged**
