### PR TITLE
Upgrade openssl to 3.0.8

### PR DESCRIPTION
**Pull request by kjup**
Remake of PR #945 with proper commit history.

### CODE REVIEW

**Comment by xclaesse** [comment]
Better to "push -f" to your initial PR to keep comments history.

**Comment by kjup** [comment]
I deleted and recreated the branch, so, I'm not sure how to push to 945?

**Comment by xclaesse** [comment]
You deleted the branch locally? Just recreate it and push again, should be fine.

**Comment by xclaesse** [comment]
Hm, anyway, let's reopen it here then, just keep in mind in the future that you can force push to existing PRs ;)

**Pull request merged**
