### PR TITLE
Fix libpng not being correctly set up with msvc

### PR DESCRIPTION
**Pull request by HaSa1002**
This fixes `libpng` not correctly working with msvc because `cc.get_define` can return empty spaces. Thus the check failes and wrong assumptions in the build script are made.

Note: This may be an actual bug, but this fix enables usage with meson 0.61.2.

### CODE REVIEW

**Comment by xclaesse** [comment]
If that's something MSVC always do, I'm wondering if we should fix that at Meson level maybe?

**Comment by eli-schwartz** [comment]
Yeah, likewise this makes me nervous that our MSVC handling is wrong.

**Comment by xclaesse** [comment]
Did a quick check this works fine with MSVC, `cc.get_define('__ANDROID__')` returns empty string.

**Comment by xclaesse** [comment]
@HaSa1002 do you have more details under what circumstances this happens?

**Comment by HaSa1002** [comment]
@xclaesse I am experimenting with stuff in this tree of my repo https://github.com/HaSa1002/pulsar/tree/add-vision. The setup may be crap (I don't know tbh. It is a learn project). Previously, I tried to make use of vcpkg and install libraries and let meson get those dependencies through pkg-cofnig. However meson? decided to dynamically link the static library (it was linking it as shared library but linked against the .lib file). Anyway back to the topic. On my windows dev machine, I have a few build directories. One using mingw g++, one for clang, and one for msvc. I invoke and use the last one by using the `x64 native dev environment tools` for Visual Studio 2019. When I invoke `meson setup builddir --wipe` the setup fails because it returns two or three spaces instead of an empty string. Hence this fix.

My MSVC CI run fail with the same error: https://github.com/HaSa1002/pulsar/runs/5664591063?check_suite_focus=true
This indicates `cc.get_define('__ANDROID__')` is not an empty string.
You can find the workflow file here: https://github.com/HaSa1002/pulsar/blob/add-vision/.github/workflows/windows.yml#L98-L179

I hope this helps to reproduce the issue. I am genuinely afraid that it may not be reproducible. Perhaps the dev environment causes a different behaviour. I read that this should be *the* way to get msvc work correctly because of paths and other environment variable shebang.

**Comment by eli-schwartz** [comment]
It would be good to print `build\meson-logs\meson-log.txt` on failure because that file is hard to otherwise get out of a CI environment.

It should have more debug-level details about what meson did/found.

**Comment by xclaesse** [comment]
> It would be good to print `build\meson-logs\meson-log.txt` on failure because that file is hard to otherwise get out of a CI environment.

With gitlab CI we attach that file in artifacts on failure, but I don't know how to do that in github. Printing is good enough I guess.

**Comment by xclaesse** [comment]
> When I invoke `meson setup builddir --wipe` the setup fails because it returns two or three spaces instead of an empty string.

Oh, it happens only on a reconfigure with --wipe, not the initial configuration or if you `rm -rf` the builddir first? That could indicate a bug in meson cache maybe.

**Comment by HaSa1002** [comment]
> It would be good to print build\meson-logs\meson-log.txt on failure because that file is hard to otherwise get out of a CI environment.

There you go: [CI Run](https://github.com/HaSa1002/pulsar/runs/5676079287?check_suite_focus=true)
<details>
<summary>Log</summary>

```console
Build started at 2022-03-24T12:15:09.405704
Main binary: C:\Users\runneradmin\scoop\apps\meson\current\meson.exe
Build Options: -Ddefault_library=static
Python system: Windows
The Meson build system
Version: 0.61.2
Source dir: D:\a\pulsar\pulsar
Build dir: D:\a\pulsar\pulsar\build
Build type: native build
Project name: pulsar
Project version: 0.1
Sanity testing C++ compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl sanitycheckcpp.cc /Fesanitycheckcpp.exe /MDd /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckcpp.cc

-----
Sanity check compile stderr:

-----
Running test binary command: D:\a\pulsar\pulsar\build\meson-private\sanitycheckcpp.exe
C++ compiler for the host machine: cl (msvc 19.31.31104 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64")
C++ linker for the host machine: link link 14.31.31104.0
Sanity testing C++ compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl sanitycheckcpp.cc /Fesanitycheckcpp.exe /MDd /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckcpp.cc

-----
Sanity check compile stderr:

-----
Running test binary command: D:\a\pulsar\pulsar\build\meson-private\sanitycheckcpp.exe
C++ compiler for the build machine: cl (msvc 19.31.31104 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64")
C++ linker for the build machine: link link 14.31.31104.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Adding test "core_test"
Pkg-config binary for 1 is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default Pkg-config fallback at pkg-config
Found pkg-config: C:\Users\runneradmin\scoop\shims\pkg-config.EXE (0.26)
Determining dependency 'sdl2' with pkg-config executable 'C:\\Users\\runneradmin\\scoop\\shims\\pkg-config.EXE'
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --modversion sdl2` -> 0
2.0.20
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --cflags sdl2` -> 0
-IC:/Users/runneradmin/scoop/apps/sdl2/2.0.20/include/SDL2
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --libs sdl2` -> 0
-LC:/Users/runneradmin/scoop/apps/sdl2/2.0.20/lib -lSDL2
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --libs sdl2` -> 0
-LC:/Users/runneradmin/scoop/apps/sdl2/2.0.20/lib -lSDL2
Running compile:
Working directory:  D:\a\pulsar\pulsar\build\meson-private\tmp64z5ltkz
Command line:  cl D:\a\pulsar\pulsar\build\meson-private\tmp64z5ltkz\testfile.cpp /FeD:\a\pulsar\pulsar\build\meson-private\tmp64z5ltkz\output.exe /nologo /showIncludes /utf-8 /MDd /nologo /showIncludes /utf-8 /Od /Oi- 

Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        }
Compiler stdout:
 testfile.cpp
Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stdio.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt.h
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\vcruntime.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\sal.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\concurrencysal.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\vadefs.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_wstdio.h
Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_stdio_config.h

Compiler stderr:
 
Program stdout:

8

Program stderr:


Run-time dependency sdl2 found: YES 2.0.20
Pkg-config binary for 1 is cached.
Determining dependency 'gl' with pkg-config executable 'C:\\Users\\runneradmin\\scoop\\shims\\pkg-config.EXE'
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --modversion gl` -> 1

Run-time dependency gl found: YES
Pkg-config binary for 1 is cached.
Determining dependency 'libpng' with pkg-config executable 'C:\\Users\\runneradmin\\scoop\\shims\\pkg-config.EXE'
env[PKG_CONFIG_PATH]: C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig; C:\Users\runneradmin\scoop\apps\sdl2\2.0.20\lib\pkgconfig;
Called `C:\Users\runneradmin\scoop\shims\pkg-config.EXE --modversion libpng` -> 1

CMake binary for 1 is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.22.3)
Extracting basic cmake information
CMake Toolchain: Calling CMake once to generate the compiler state
Calling CMake (['C:\\Program Files\\CMake\\bin\\cmake.EXE']) in D:\a\pulsar\pulsar\build\meson-private\__CMake_compiler_info__ with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-G"
  - "Ninja"
  - "-DCMAKE_TOOLCHAIN_FILE=D:/a/pulsar/pulsar/build/meson-private/__CMake_compiler_info__/CMakeMesonTempToolchainFile.cmake"
  - "."
!meson_ci!/ci_include "D:/a/pulsar/pulsar/build/meson-private/cmake_libpng/CMakeMesonToolchainFile.cmake"
Try CMake generator: auto
!meson_ci!/ci_include "D:/a/pulsar/pulsar/build/meson-private/cmake_libpng/CMakeLists.txt"
Calling CMake (['C:\\Program Files\\CMake\\bin\\cmake.EXE']) in D:\a\pulsar\pulsar\build\meson-private\cmake_libpng with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=D:/a/pulsar/pulsar/build/meson-private/cmake_libpng/CMakeMesonToolchainFile.cmake"
  - "."
  -- Module search paths:    ['C:/Program Files', 'C:/Program Files (x86)', 'C:/Program Files/CMake']
  -- CMake root:             C:/Program Files/CMake/share/cmake-3.22
  -- CMake architectures:    []
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share']
Preliminary CMake check failed. Aborting.
Run-time dependency libpng found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libpng
Downloading libpng source from https://github.com/glennrp/libpng/archive/v1.6.37.tar.gz
Downloading libpng patch from https://wrapdb.mesonbuild.com/v2/libpng_1.6.37-5/get_patch

Executing subproject libpng 

Project name: libpng
Project version: 1.6.37
Sanity testing C compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl sanitycheckc.c /Fesanitycheckc.exe /MDd /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckc.c

-----
Sanity check compile stderr:

-----
Running test binary command: D:\a\pulsar\pulsar\build\meson-private\sanitycheckc.exe
C compiler for the host machine: cl (msvc 19.31.31104 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64")
C linker for the host machine: link link 14.31.31104.0
Sanity testing C compiler: cl
Is cross compiler: False.
Sanity check compiler command line: cl sanitycheckc.c /Fesanitycheckc.exe /MDd /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckc.c

-----
Sanity check compile stderr:

-----
Running test binary command: D:\a\pulsar\pulsar\build\meson-private\sanitycheckc.exe
C compiler for the build machine: cl (msvc 19.31.31104 "Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64")
C linker for the build machine: link link 14.31.31104.0
Running compile:
Working directory:  C:\Users\RUNNER~1\AppData\Local\Temp\tmp0fh5lkfi
Command line:  cl C:\Users\RUNNER~1\AppData\Local\Temp\tmp0fh5lkfi\testfile.c /nologo /showIncludes /utf-8 /EP /nologo /showIncludes /utf-8 /EP /Od /Oi- /std:c11 

Code:
 
        
        #ifndef __ANDROID__
        # define __ANDROID__
        #endif
        "MESON_GET_DEFINE_DELIMITER"
__ANDROID__
Compiler stdout:
 

        
        
        
        
        "MESON_GET_DEFINE_DELIMITER"
 

Compiler stderr:
 testfile.c

Fetching value of define "__ANDROID__" :   
Running compile:
Working directory:  D:\a\pulsar\pulsar\build\meson-private\tmpduxp56j5
Command line:  cl D:\a\pulsar\pulsar\build\meson-private\tmpduxp56j5\testfile.c /FeD:\a\pulsar\pulsar\build\meson-private\tmpduxp56j5\output.exe /nologo /showIncludes /utf-8 /MDd /nologo /showIncludes /utf-8 /Od /Oi- z.lib /link /nologo /release /nologo 

Code:
 int main(void) { return 0; }

Compiler stdout:
 testfile.c
LINK : fatal error LNK1181: cannot open input file 'z.lib'

Compiler stderr:
 
Running compile:
Working directory:  D:\a\pulsar\pulsar\build\meson-private\tmp1_g1e2_v
Command line:  cl D:\a\pulsar\pulsar\build\meson-private\tmp1_g1e2_v\testfile.c /FeD:\a\pulsar\pulsar\build\meson-private\tmp1_g1e2_v\output.exe /nologo /showIncludes /utf-8 /MDd /nologo /showIncludes /utf-8 /Od /Oi- 

Code:
 #include<stdio.h>
        
        int main(void) {
            printf("%ld\n", (long)(sizeof(void *)));
            return 0;
        }
Compiler stdout:
 testfile.c
Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stdio.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt.h
Note: including file:   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\vcruntime.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\sal.h
Note: including file:     C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\concurrencysal.h
Note: including file:    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\vadefs.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_wstdio.h
Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_stdio_config.h

Compiler stderr:
 
Program stdout:

8

Program stderr:



subprojects\libpng-1.6.37\meson.build:15:2: ERROR: C shared or static library 'z' not found
```

</details>

> Oh, it happens only on a reconfigure with --wipe, not the initial configuration or if you rm -rf the builddir first? That could indicate a bug in meson cache maybe.

It happens with both.

**Comment by xclaesse** [comment]
Ok, this is super weird. Here is my output with MSVC 19.29.30141:

```
__ANDROID__
Compiler stdout:






        "MESON_GET_DEFINE_DELIMITER"


Compiler stderr:
```

Your output with MSVC 19.31.31104:
```
Fetching value of define "__ANDROID__" :


        "MESON_GET_DEFINE_DELIMITER"
 

Compiler stderr:
```

There is indeed a white space added, you can see it if you copy/pate to an editor that show white spaces. I guess this is a regression^Wfancy new behaviour of MSVC...

**Comment by HaSa1002** [comment]
Oh wow.

**Comment by xclaesse** [comment]
@HaSa1002 I have VisualStudio 2019, I guess you have 2022?

**Comment by HaSa1002** [comment]
No, I use 2019. It isn't even up to date. (16.8.4 and the build tools [which I see the first time today) are 16.11.10 according to the vs installer)

**Comment by xclaesse** [comment]
Weird, VS installer says it's up to date here. According to [wikipedia](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B):
```
14.29 | 1929 (Visual Studio 2019 Version 16.10 + 16.11)
14.30 | 1930 (Visual Studio 2022 Version 17.0)
14.31 | 1931 (Visual Studio 2022 Version 17.1)
```

**Comment by xclaesse** [comment]
Weird... in any case, this will have to be fixed in Meson, not in libpng wrap. Can you please report the issue? Closing this PR.

**Comment by xclaesse** [comment]
Installed VS 2022 to try this, it has MSVC 19.31.31105 (one revision above yours) and I don't have that extra space. Maybe something is different in your system local? Dunno...

**Comment by HaSa1002** [comment]
Thing is. It happens both on CI and my machine. This super weird.

**Comment by xclaesse** [comment]
And we can't just strip, the space could be intentional in the macro, even if unlikely. OOC, does that happen for every defines? Does it add white space to defines that exists?

**Comment by HaSa1002** [comment]
I did test this with `__WIN32`...
```
 

        
        
        
        
        "MESON_GET_DEFINE_DELIMITER"
 

```

**Comment by HaSa1002** [comment]
Edit: `__WIN32` is not defined. I did another test with `_WIN32` resulting in correct behaviour:

```
Code:
 
        
        #ifndef _WIN32
        # define _WIN32
        #endif
        "MESON_GET_DEFINE_DELIMITER"
_WIN32
Compiler stdout:
 

        
        


        "MESON_GET_DEFINE_DELIMITER"
1 

Compiler stderr:
 testfile.c

Fetching value of define "_WIN32" : 1  
```

**Comment by HaSa1002** [comment]
> Weird... in any case, this will have to be fixed in Meson, not in libpng wrap. Can you please report the issue? Closing this PR.

Done. See https://github.com/mesonbuild/meson/issues/10179

**Pull request closed without merging**
