### PR TITLE
Add c-ares unit tests, export symbols on MSVC required by unit tests

### PR DESCRIPTION
**Pull request by klokik**
This will help to address linking issues that may be encountered by users in different configurations

### CODE REVIEW

**Comment by neheb** [comment]
Unit tests require private symbols?

**Comment by klokik** [comment]
Unfortunatelly yes. Or a separate static library that will be used for the test-suite executable.

**Comment by neheb** [comment]
I think the latter is more widely done here.

**Comment by klokik** [comment]
https://github.com/c-ares/c-ares/blob/4982f76a2f7a0d629c32370427a689584443e3ea/CMakeLists.txt#L49

**Comment by klokik** [comment]
Maybe, but primarily l want this unit test here to have an easy-to-reach sample user of the library, to make sure that it does not have unexpected linking issues somewhere. Like the previous version was causing undefined symbols because of missing `compile_args` provided by `cares_dep` in the case of the static build.

**Comment by benoit-pierre** [comment]
Do the tools require private symbols too? If not, that can be used to test linking with the final library, while linking the tests with a static version.

**Comment by klokik** [comment]
Yes: at least on windows `tools` use an internal wrapper implementing `strcasecmp()`.

**Comment by klokik** [comment]
How bad is it exporting these internal symbols only if `tests` flags is set?

**Comment by benoit-pierre** [comment]
It's kinda icky to get a different library whether you enabled tests or not.

**Comment by klokik** [comment]
All these functions are properly prefixed so unlikely to cause collisions. But I dread to think of using `--export-all-symbols` on windows+gcc

**Comment by klokik** [comment]
Rebased, that was a pain due to a sneaky formatting change. Thanks @neheb :upside_down_face: 

No hacky symbols exporting this time: building static lib for tools and unit tests if required.

**Comment by neheb** [comment]
:)

Should have waited before merging. Oh well.

**Pull request merged**
