### PR TITLE
libpng: Add MSVC assembly support for arm64

### PR DESCRIPTION
**Pull request by gaborkertesz-linaro**
MSVC supports arm64 on Windows on Arm, starting with Visual
Studio 2019.
MSVC assembler requires explicit C preprocessor call if
C preprocessor language is used in the assembly source file.
So arm/filter_neon.S is preprocessed then passed to assembler,
if MSVC is used.

### CODE REVIEW

**Comment by gaborkertesz** [comment]
Can I help in anything to move forward with this change?

**Comment by eli-schwartz** [comment]
Thanks for reminding me!

Seems like this is missing the revision bump in releases.json, without which this won't release a new version of the wrap.

**Comment by gaborkertesz-linaro** [comment]
Is my understanding aoout json versioning is correct, where the "1.6.37" is the libpng version and the "-3" is the version of the supporting wrap?
I was a bit confused, because the last digits of 1.6.17 versions are not contiguous.

**Comment by gaborkertesz-linaro** [comment]
Do you mean this https://github.com/mesonbuild/wrapdb/blob/master/ci_config.json#L17 ?

**Pull request merged**
