### PR TITLE
hinnant-date: update to 3.0.1

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by jpakkane** [comment]
LGTM, but currently ⚔️ conflicts.

**Comment by jpakkane** [comment]
Still does...

**Comment by neheb** [comment]
The snappy commit broke it. Disadvantage of avoiding clang-format on ci_config.json.

**Comment by neheb** [comment]
Fixed again.

**Comment by jpakkane** [comment]
Great, thanks.

**Comment by eli-schwartz** [comment]
I'm disappointed that this PR was merged despite it being *literally* a duplicate of #305

If it was acceptable to merge an update that intentionally disables CI because the wrap is conceptually flawed, then we should have merged #305 -- if not, then my review comments for #305 still apply to this PR. Either way it should not be merged.

:/

**Comment by eli-schwartz** [comment]
So I just want to clarify -- "then we should have merged #305".

The main problem I have with this PR is it seems fundamentally dishonest to reject someone's work "because foo", then have someone else resubmit the same PR under their own name, not fix "foo", and be golden.

In short, I'm disappointed that you left that PR to rot instead of responding *there* that "this is a 1:1 port of upstream". Regardless of anything to do with specific wraps, I'd greatly appreciate it if we could do better than that in the future.

**Pull request merged**
