### PR TITLE
glib: update to 2.76.4

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by bgilbert** [comment]
Visual Studio tests are failing with the usual CMake problem:

```
glib| WARNING: CMake Toolchain: Failed to determine CMake compilers state
```

MSYS2-CLANG64 is failing without any real explanation:

```
[38/677] Generating symbol file subprojects/pcre2-10.42/libpcre2-8-0.dll.p/libpcre2-8-0.dll.symbols
FAILED: subprojects/pcre2-10.42/libpcre2-8-0.dll.p/libpcre2-8-0.dll.symbols 
"D:/a/_temp/msys64/clang64/bin/meson" "--internal" "symbolextractor" "D:/a/wrapdb/wrapdb/_build" subprojects/pcre2-10.42/libpcre2-8-0.dll "subprojects/pcre2-10.42/libpcre2-8.dll.a" subprojects/pcre2-10.42/libpcre2-8-0.dll.p/libpcre2-8-0.dll.symbols 
```

**Comment by eli-schwartz** [comment]
The msys2 issue is innocent enough, restarting CI usually helps there. For a long time it was pretty baffling, python.exe inside of an msys2 shell would segfault but only sometimes, and only in a combination of:
- running from Github Actions
- spawned by ninja instead of run directly
- debugger is not enabled

The issue disappeared again in python 3.11 but msys2 is still working on updating that I guess.

**Comment by eli-schwartz** [comment]
Your push canceled my attempt to rerun it.

**Comment by bgilbert** [comment]
Ah, wasn't sure if you were planning to do it.  Since I don't have privileges here, a force-push is the only way I can rerun.

**Comment by bgilbert** [comment]
Okay cool, just Visual Studio now.

**Comment by eli-schwartz** [comment]
If anyone has an idea how to fix https://github.com/mesonbuild/meson/issues/11521 that would be neat... I do not know much of anything about the cmake integration unfortunately...

**Pull request merged**
