### PR TITLE
htslib: update to 1.20

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Anyone know why build_on: windows: false is not working?

**Comment by benoit-pierre** [comment]
It's unrelated, no?
```
AssertionError: '0.28.3-1' not found in ['0.28.1-1', '0.28.0-1'] : for exiv2
```
Need a rebase, maybe?

**Comment by neheb** [comment]
That's the clang64 error. indeed unrelated. I'm talking about the visual studio ones.

**Comment by benoit-pierre** [comment]
Ubuntu:
```
   * [new tag]           exiv2_0.28.0-1              -> exiv2_0.28.0-1
   * [new tag]           exiv2_0.28.1-1              -> exiv2_0.28.1-1
```
MSVC:
```
   * [new tag]           exiv2_0.28.0-1              -> exiv2_0.28.0-1
   * [new tag]           exiv2_0.28.1-1              -> exiv2_0.28.1-
   * [new tag]           exiv2_0.28.3-1              -> exiv2_0.28.3-1
```

I don't know why they pick up different tags, but I guess you do need a rebase.

**Comment by neheb** [comment]
I'm talking about

```
 subprojects\htslib-1.20\meson.build:12:2: ERROR: Problem encountered: MSVC is unsupported. Only MinGW.
```

build_on: windows: false is specified in ci_config.json. I'm asking why it's not working for the other visual studios.

**Comment by benoit-pierre** [comment]
Oh, OK.

**Comment by neheb** [comment]
And now it's working...

**Pull request merged**
