### PR TITLE
Fix project() 'version' argument in sdl2_image

### PR DESCRIPTION
**Pull request by germandiagogomez**
sdl2_image wrap project patch does not include version number. Fixed in this PR, was creating trouble for a dependency in my project.

### CODE REVIEW

**Comment by jpakkane** [comment]
You need to update the version json file as well.

**Comment by germandiagogomez** [comment]
@jpakkane is that the right way to do it?

**Comment by eli-schwartz** [comment]
Yes, but it should be squashed into one commit.

**Comment by germandiagogomez** [comment]
Done

**Comment by jpakkane** [comment]
The ubuntu test failure is due to missing deps? The Windows one is unclear, but probably not caused by this change?

**Comment by germandiagogomez** [comment]
Is there any way in which I can help? Indeed the Ubuntu one seems like a missing dependency in the machine running the CI. 

No idea what happens on Windows side.

**Comment by eli-schwartz** [comment]
The sdl2 wrap needs a better CI config, I guess. But see also #218

**Pull request merged**
