### PR TITLE
add pugixml version 1.12-1

### PR DESCRIPTION
**Pull request by bitrunner**

### CODE REVIEW

**Comment by jpakkane** [comment]
I tried to build this locally on Windows and it worked fine. No idea what could be the problem here.

**Comment by eli-schwartz** [comment]
Please rebase on master and drop the second commit.

**Comment by jpakkane** [comment]
Which is to say that the CI environment has been updated so a rebase should make this pass.

**Comment by bitrunner** [comment]
Thanks Jussi and Eli!  I didn't have a clue what was wrong with the windows CI.

**Pull request merged**
