### PR TITLE
fuse: clean up meson build

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by eli-schwartz** [comment]
IIRC this was mainly copied from the fuse3 branch as a backport for people stuck with old versions of fuse. Not sure how worth it it is to rewrite that.

I'm especially extremely skeptical of using extremely recent features of Meson such as the new custom dependencies. The main purpose of *old* versions of fuse is probably for people on old systems with old Meson, and either way this doesn't even declare the minimum required version of Meson.

**Comment by neheb** [comment]
Makes sense. There are libfuse3 typos in here.

The dependency stuff doesn't seem like a big deal to me. Iconv is not required. Maybe dl is.

**Comment by xclaesse** [comment]
Maybe update the wrap to upstream fuse3, those who are stuck with old fuse2 can still use old wraps.

**Comment by neheb** [comment]
fuse 2 and 3 use different pkgconfig names. I don't see why they should be mutually exclusive.

**Comment by xclaesse** [comment]
> fuse 2 and 3 use different pkgconfig names. I don't see why they should be mutually exclusive.

oh, should be different wraps then, indeed.

**Comment by neheb** [comment]
@eli-schwartz added fallbacks for older meson versions.

**Pull request merged**
