### PR TITLE
Upgrade libuv to 1.44.2

### PR DESCRIPTION
**Pull request by nazar-pc**
Based on upstream `CMakeLists.txt` changes

### CODE REVIEW

**Comment by nazar-pc** [comment]
Not sure what happened to macOS. Test must be racy, it succeeded in my fork: https://github.com/nazar-pc/wrapdb/actions/runs/2084433787

**Comment by neheb** [comment]
Maybe disable tests in ci_config with a comment

**Comment by nazar-pc** [comment]
Hm... someone submitted duplicate of this PR that was merged 2 weeks ago: https://github.com/mesonbuild/wrapdb/pull/418
Maybe it'll fix it, maybe not, not sure. It is unfortunate that that PR didn't include all of the necessary changes done upstream like this one.

**Comment by xclaesse** [comment]
argh, and it's me who merged it, oops. Could you rebase your changes on top maybe?

**Comment by nazar-pc** [comment]
I think we should just wait for 1.44.2 to be released, the changes here are for GNU Hurd, so probably not urgent for most people

**Comment by nazar-pc** [comment]
@xclaesse libuv 1.44.2 was released yesterday, have just updated PR with it. Also bumped C to `gnu99` so tests with `pthread_rwlock_t` compile.

**Pull request merged**
