### PR TITLE
sfml: update to 2.6.0

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
ping @eli-schwartz for the vulkan change. you complained earlier about it.

**Comment by neheb** [comment]
confusingly:

```
mangix@Mangix-PC CLANG32 ~/devstuff/hashcat
$ find /clang32/share/ | grep Vulkan
/clang32/share/cmake/Help/module/FindVulkan.rst
/clang32/share/cmake/Modules/FindVulkan.cmake
/clang32/share/cmake/VulkanHeaders
/clang32/share/cmake/VulkanHeaders/VulkanHeadersConfig.cmake
/clang32/share/cmake/VulkanHeaders/VulkanHeadersConfigVersion.cmake

mangix@Mangix-PC CLANG32 ~/devstuff/hashcat
$ find /clang32/share/ | grep OpenCL
/clang32/share/cmake/Help/module/FindOpenCL.rst
/clang32/share/cmake/Modules/FindOpenCL.cmake
/clang32/share/cmake/OpenCLHeaders
/clang32/share/cmake/OpenCLHeaders/OpenCLHeadersConfig.cmake
/clang32/share/cmake/OpenCLHeaders/OpenCLHeadersConfigVersion.cmake
/clang32/share/cmake/OpenCLHeaders/OpenCLHeadersTargets.cmake
/clang32/share/pkgconfig/OpenCL-Headers.pc
```

if they end up adding a pkgconfig file, it'll probably be named Vulkan-Headers.pc.

**Comment by eli-schwartz** [comment]
:( we can cross that bridge when we come to it but for now we can go with the decisions they have actually made.

:+1:, it's good to see some way to move forward on that package.

**Comment by jpakkane** [comment]
Fine by me.

**Pull request merged**
