### PR TITLE
liblzma: fix dep name

### PR DESCRIPTION
**Pull request by neheb**
There's no liblzma_dep anywhere.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

@eli-schwartz surprised this was not a hard error.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Apparently it was simply broken since the original implementation in #162

Making it a hard error would require somehow checking the variables exported by a meson.build, hmm...

**Comment by eli-schwartz** [comment]
I tried to implement this in #584 and it seems to work, what do you think?

**Comment by neheb** [comment]
Broken since initial PR. Incredible. I'm assuming nobody has ever used it?

**Comment by eli-schwartz** [comment]
Well, that or they just used the `fallback:` kwarg...

**Comment by jpakkane** [comment]
[I have used it personally](https://github.com/jpakkane/parzip/blob/master/meson.build). Dunno why it did not work, maybe I had not tried that particular version on non-Linux.

**Comment by eli-schwartz** [comment]
That does fail to build with `--wrap-mode=forcefallback`.

Also it doesn't use lzma at all on windows, dunno why, so that may have narrowed down the scope of the effects.

**Comment by neheb** [comment]
I noticed this issue with libtiff when I was testing the dependencies. It refused to work because of wrong name.

My Debian install does not have liblzma-dev installed. Just zlib-dev.

**Pull request merged**
