### PR TITLE
catch2: update to 3.4.0

### PR DESCRIPTION
**Pull request by haydenmc**

### CODE REVIEW

**Comment by neheb** [comment]
do you happen to know the deal with https://github.com/mesonbuild/wrapdb/blob/master/subprojects/catch.wrap? That's not catch1.

**Comment by neheb** [comment]
```
..\subprojects\Catch2-3.4.0\src\catch2/catch_tostring.hpp(71,56): warning: implicit conversion between pointer-to-function and pointer-to-object is a Microsoft extension [-Wmicrosoft-cast]
                -> decltype(std::declval<Stream&>() << std::declval<U>(), std::true_type());
                                                       ^~~~~~~~~~~~~~~~~
..\subprojects\Catch2-3.4.0\src\catch2/catch_tostring.hpp(520,84): note: in instantiation of template class 'Catch::Detail::IsStreamInsertable<void (void *)>' requested here
    struct StringMaker<R, std::enable_if_t<is_range<R>::value && !::Catch::Detail::IsStreamInsertable<R>::value>> {
                                                                                   ^
..\subprojects\Catch2-3.4.0\src\catch2/catch_tostring.hpp(150,29): note: during template argument deduction for class template partial specialization 'StringMaker<R, std::enable_if_t<is_range<R>::value && !::Catch::Detail::IsStreamInsertable<R>::value>>' [with R = void (void *)]
            return ::Catch::StringMaker<std::remove_cv_t<std::remove_reference_t<T>>>::convert(e);
                            ^
..\subprojects\Catch2-3.4.0\src\catch2/catch_tostring.hpp(150,29): note: in instantiation of template class 'Catch::StringMaker<void (void *)>' requested here
..\subprojects\Catch2-3.4.0\src\catch2/internal/catch_decomposer.hpp(80,42): note: in instantiation of function template specialization 'Catch::Detail::stringify<void (void *)>' requested here
                    ( os, Catch::Detail::stringify( m_lhs ), m_op, Catch::Detail::stringify( m_rhs ) );
                                         ^
../subprojects/Catch2-3.4.0/tests/SelfTest/UsageTests/Compilation.tests.cpp(208,49): note: in instantiation of member function 'Catch::BinaryExpr<void (&)(void *), void (*&)(void *)>::streamReconstructedExpression' requested here
        REQUIRE(utility::synchronizing_callback != test.testMethod_uponComplete_arg);
```

hrm

**Comment by haydenmc** [comment]
> do you happen to know the deal with https://github.com/mesonbuild/wrapdb/blob/master/subprojects/catch.wrap? That's not catch1.

No clue on this, sorry! I'm not affiliated with Catch at all, I just consume it in a lot of my projects. It does look like catch1 is at least semi-maintained, as the [branch](https://github.com/catchorg/Catch2/commits/Catch1.x) has seen commits as recently as Jan '23 - so perhaps we've got 2 instances of Catch2 represented here. 😬

Per the compiler warnings, I see this issue on the Catch2 repo: https://github.com/catchorg/Catch2/issues/2048. That seems to indicate it's known, or at least has existed since 3.0.0.

**Comment by neheb** [comment]
2 instances...yeah.

**Pull request merged**
