### PR TITLE
Update cJSON to 1.7.15

### PR DESCRIPTION
**Pull request by tristan957**

### CODE REVIEW

**Comment by tristan957** [comment]
I wasn't too sure on what the protocol for tests was, but they are there and they pass so yay!

**Comment by eli-schwartz** [comment]
Cool, thanks!

**Comment by eli-schwartz** [comment]
I'm actually immensely puzzled by upstream, since the tests appear to mostly be in tests/ but there is also one test at https://github.com/DaveGamble/cJSON/blob/master/test.c ?

**Comment by tristan957** [comment]
lol. cJSON upstream is something else...

**Pull request merged**
