### PR TITLE
pugixml: update to 1.13

### PR DESCRIPTION
**Pull request by neheb**
Use declspec on MinGW too. It works there too.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Preparation for version 1.13 which drops Nov 1.

### CODE REVIEW

**Comment by neheb** [comment]
This is ready.

```
 FileNotFoundError: [Errno 2] No such file or directory: 'meson'
```

not related to this PR.

**Comment by neheb** [comment]
@jpakkane this is ready

**Comment by eli-schwartz** [comment]
It's related to the PR in the sense that it's currently a blocker for running macOS CI at all.

I was planning to investigate this on Sunday. Please do not merge any PRs until we have working CI, but feel free to investigate the problem yourself earlier.

**Comment by neheb** [comment]
this PR is fine. https://github.com/mesonbuild/wrapdb/actions/runs/3349745929 shows a successful run.

**Pull request merged**
