### PR TITLE
Add cimg

### PR DESCRIPTION
**Pull request by v1993**
Add [cimg](https://cimg.eu/) - an image processing library for C++. While library itself is header-only, it has a rather wide range of configuration options, including support for other (non-header-only) libraries. As such, it makes for a rather sizable amount of meson options.

It does not include tests, so I've opted to enable building examples it ships with in CI.

### CODE REVIEW

**Comment by v1993** [comment]
Guess I just should stop defining `cimg_use_openmp` altogether... Code from library, indented and commented for clarity:

```cpp
#if !defined(cimg_use_openmp)
  #ifdef _OPENMP
    #define cimg_use_openmp 1
  #else
    #define cimg_use_openmp 0
  #endif
#else
  // WTF???
  #undef cimg_use_openmp
  #define cimg_use_openmp 1
#endif

#if cimg_use_openmp!=0
  #include <omp.h>
  #define cimg_pragma_openmp(p) cimg_pragma(omp p)
#else
  #define cimg_pragma_openmp(p)
#endif
```

**Comment by v1993** [comment]
Looks like apple's clang defines `_OPENMP` without providing actual OpenMP support? Just great. Guess I'll have to try to install libomp from brew and pray that works...

In the meantime, on Windows clang-cl decided to warn about deprecated functions despite file defining constants that should prevent that from happening. Good job, two different yet equally painful variations of clang...

**Comment by v1993** [comment]
Alright, now both builds are failing because of OpenMP issues - MacOS still can't find OpenMP even when installed from homebrew and clang-cl fails at linking step due to unresolved references to functions from supporting OpenMP library (meson bug?). Kinda clueless what to do next.

**Comment by jpakkane** [comment]
If no-one can come up with a solution, then you can tag it so CI won't try to build it. It's better than not having it available at all.

**Comment by neheb** [comment]
to fix clang-cl you need something like this: https://github.com/mesonbuild/wrapdb/commit/528f003861aac7cfb0124f1766eb264abdc4305f

upstream meson bug: https://github.com/mesonbuild/meson/pull/11648/commits/2d60aa6b393177cb6e8fa3504c2568217dde2f64

**Comment by neheb** [comment]
brew.sh 's libomp is Keg-only. meaning you need to add non default paths to use it.

**Comment by v1993** [comment]
I'm no longer interested in this library (decided to go with a different solution), so closing this PR. It should be a fairly solid foundation in case someone decides to get this finished and merged.

**Pull request closed without merging**
