### PR TITLE
[WIP] Add xxhash 0.8.1 support

### PR DESCRIPTION
**Pull request by ninjaoflight**
adds support for `xxhash 0.8.1` (#247)
- tested with `Arch Linux` with `Clang 13.0.1`
- checked with `Windows` with `Clang 13.0.0`
this will fix also #314 on 0.8.1

### CODE REVIEW

**Comment by eli-schwartz** [comment]
CI failure because the project() version hasn't been updated.

**Comment by ninjaoflight** [comment]
Done, I also changed the windows configuration of #314 so it checks for windows instead of clang and MSVC.

**Comment by eli-schwartz** [comment]
This has a merge commit in it, please [rebase](https://git-scm.com/docs/git-rebase) to two distinct commits:
- one to fix the Windows export handling (and associated refactor)
- one to bump the version to 0.8.1


(If you aren't used to rebasing -- I suggest working on a new local branch, getting the commit history sorted out, and then force pushing to the PR branch.)

**Comment by ninjaoflight** [comment]
Done

**Pull request merged**
