### PR TITLE
harfbuzz: update to 8.2.0

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by jpakkane** [comment]
` subprojects/libffi-3.4.4/src/preprocessor_0.p/win64_intel.masm(2) : error A2008:syntax error : .`

Seems like an issue with ffi. But why is it not happening on other projects?

**Comment by benoit-pierre** [comment]
I don't know, but it's the same as last time.

**Comment by benoit-pierre** [comment]
With just a release bump for the CI, libffi Windows builds fail: https://github.com/benoit-pierre/wrapdb/actions/runs/6134683080.

**Comment by benoit-pierre** [comment]
The MSYS failure is different though, I think it's an issue with meson not using response files with some compilers that support it. Something I already investigated but have not reported to the project.

**Comment by benoit-pierre** [comment]
OK, I remember now, when using `lld` for linking, e.g. with this config:
```ini
[binaries]
c='clang'
c_ld='lld'
```

Then response file are never used. (Easily testable by using `export MESON_RSP_THRESHOLD=0`).

**Comment by benoit-pierre** [comment]
```python
▸ python <<'EOF'
from mesonbuild.linkers.linkers import LLVMDynamicLinker
print(LLVMDynamicLinker(['lld'], '', '', []).get_accepts_rsp())
EOF
False
```
And with this patch:
```diff
diff --git i/mesonbuild/linkers/linkers.py w/mesonbuild/linkers/linkers.py
index 0c2bf73be..641dee2fe 100644
--- i/mesonbuild/linkers/linkers.py
+++ w/mesonbuild/linkers/linkers.py
@@ -611,6 +611,9 @@ class GnuLikeDynamicLinkerMixin(DynamicLinkerBase):
         "boot_application": "16",
     }
 
+    def get_accepts_rsp(self) -> bool:
+        return True
+
     def get_buildtype_args(self, buildtype: str) -> T.List[str]:
         # We can override these in children by just overriding the
         # _BUILDTYPE_ARGS value.
@@ -846,9 +849,6 @@ class GnuDynamicLinker(GnuLikeDynamicLinkerMixin, PosixDynamicLinkerMixin, Dynam
 
     """Representation of GNU ld.bfd and ld.gold."""
 
-    def get_accepts_rsp(self) -> bool:
-        return True
-
 
 class GnuGoldDynamicLinker(GnuDynamicLinker):
 
```
```python
▸ python <<'EOF'
from mesonbuild.linkers.linkers import LLVMDynamicLinker
print(LLVMDynamicLinker(['lld'], '', '', []).get_accepts_rsp())
EOF
True
```

**Pull request merged**
