### PR TITLE
qrencode: add 4.1.1

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Comment by neheb** [comment]
weird that clang-cl builds but not cl...

**Comment by hrxi** [comment]
It's a problem of missing `__declspec(dllexport)`, I believe.

**Comment by neheb** [comment]
Yeah need to add a def file.

**Comment by hrxi** [comment]
Also opened an upstream PR fixing MSVC support properly: https://github.com/fukuchi/libqrencode/pull/214.

**Pull request merged**
