### PR TITLE
libopenjp2: avoid pulling-in unnecessary dependencies

### PR DESCRIPTION
**Pull request by benoit-pierre**
Example: avoid downloading & configuring a cURL subproject when using `-Dbuild_jpip_server=false --wrap-mode=forcefallback`.

I'm tempted to change the `build_jpip_server` option to a feature for simpler code, which might break some configs when updating the wrap, thoughts?

### CODE REVIEW

**Comment by neheb** [comment]
Go for it.

**Comment by benoit-pierre** [comment]
OK, never mind, I don't have the patience to go through the mess that this wrap is for now… (`curl_dep` and `fcgi_dep` are used elsewhere for no good reason in another part of that half-backed, clearly never tested port).

**Comment by neheb** [comment]
probably needs to be rewritten to modern standards honestly.

**Comment by benoit-pierre** [comment]
Yep.

**Pull request closed without merging**
