### PR TITLE
curl: pass CURL_STATICLIB for static libraries

### PR DESCRIPTION
**Pull request by Barakat**
cURL is not compiled with `CURL_STATICLIB` when building a static library. cURL symbols end up being exported in the executable.

### CODE REVIEW

**Comment by neheb** [comment]
Need a bump in releases.json. ping @benoit-pierre

**Comment by benoit-pierre** [comment]
It would be better to add `public_args` to the library `c_args`, instead of using `add_project_arguments` (which impacts all other compiled library/executables).

**Comment by Barakat** [comment]
I added `curl_lib_c_args` for this to keep these two, `public_args`, separate.

**Comment by benoit-pierre** [comment]
> I added `curl_lib_c_args` for this to keep these two, `public_args`, separate.

Why? It makes perfect sense to use `public_args`.

**Comment by Barakat** [comment]
`public_args` appears to be intended for the consumers of the library, and not for the library itself. I added `curl_lib_c_args` to make it explicit that the flags are for different audience.

**Comment by benoit-pierre** [comment]
`public_args` is for the library compilation flags that are public, exported to consumers too. So no, I don't agree with the duplication.

**Comment by Barakat** [comment]
@benoit-pierre I have passed it with `public_args`.

**Review by benoit-pierre — APPROVED** [review]

**Pull request merged**
