### PR TITLE
imgui: add docking branch as a separate dependency

### PR DESCRIPTION
**Pull request by tmayoff**
I have a lot of projects that utilize the docking branch of imgui, figured it'd be useful for others as well to have it available via wrapdb

### CODE REVIEW

**Comment by tmayoff** [comment]
Anyone have an idea on how to fix the windows/macos builds

**Comment by benoit-pierre** [comment]
It looks like it's missing a system dependency: dxgi.

**Comment by tmayoff** [comment]
It's using the same patch files as the normal imgui, and they shouldn't differ all that drastically. I couldn't see any extra configs for imgui anywhere else other than some debian packages for the CI. This should work if the normal imgui does

**Comment by benoit-pierre** [comment]
What I meant is `meson.build` need to be adapted to add the `dxgi` dependency on MSCV.

**Comment by yretenai** [comment]
This branch is now merged into main, and released as imgui v1.90.

**Comment by tmayoff** [comment]
I'm not sure if it's a good idea to be modifying the main imgui patch meson.build, but I'd like to reduce duplicate code. 

I'm not familiar enough with macos builds, so if someone knows what's happening or can debug it to help that'd be great.

**Comment by benoit-pierre** [comment]
> I'm not sure if it's a good idea to be modifying the main imgui patch meson.build, but I'd like to reduce duplicate code.

No way around it if the 2 variants need different dependencies.

> I'm not familiar enough with macos builds, so if someone knows what's happening or can debug it to help that'd be great.

It's missing a framework, this one I think:
```meson
dependency('appleframeworks', modules : 'QuartzCore')
```

**Pull request closed without merging**
