### PR TITLE
CI: don't test clang32

### PR DESCRIPTION
**Pull request by neheb**
For some reason it keeps failing on generating symbols. The other backends seem to be fine.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I don't think it has anything to do with clang32, this is a known random flake that happens in the meson CI too. That uses mingw32 and mingw64.

https://github.com/mesonbuild/meson/blob/01420bf8fc1ee6c1466e2fa4c9805267192dce26/.github/workflows/msys2.yml#L54-L56

**Comment by eli-schwartz** [comment]
There's a dirty hack to work around it, but restarting a failing job works as well.

**Comment by neheb** [comment]
The real problem is build_all

**Comment by eli-schwartz** [comment]
Nonetheless, setting winjitdebug so that msys2 detects a debugging environment and refuses to crash, seems safer.

**Comment by neheb** [comment]
I'll set to draft for now.

**Pull request closed without merging**
