### PR TITLE
libxslt: make dependent on libxml >= 2.9.10

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
@xclaesse the issue is brew's copy of libxml2

**Comment by neheb** [comment]
```
2023-03-04T00:54:42.1118160Z libxml2 is keg-only, which means it was not symlinked into /usr/local,
2023-03-04T00:54:42.1118670Z because macOS already provides this software and installing another version in
2023-03-04T00:54:42.1119110Z parallel can cause all kinds of trouble.
2023-03-04T00:54:42.1119290Z 
2023-03-04T00:54:42.1119480Z If you need to have libxml2 first in your PATH, run:
2023-03-04T00:54:42.1120360Z   echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> /Users/runner/.bash_profile
2023-03-04T00:54:42.1120650Z 
2023-03-04T00:54:42.1120830Z For compilers to find libxml2 you may need to set:
2023-03-04T00:54:42.1121320Z   export LDFLAGS="-L/usr/local/opt/libxml2/lib"
2023-03-04T00:54:42.1121890Z   export CPPFLAGS="-I/usr/local/opt/libxml2/include"
2023-03-04T00:54:42.1122130Z 
2023-03-04T00:54:42.1122620Z For pkg-config to find libxml2 you may need to set:
2023-03-04T00:54:42.1123110Z   export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgco
```

great

**Comment by xclaesse** [comment]
@neheb is it ready now? Change looks good, but will it work in build-all?

**Comment by neheb** [comment]
yes. I tested it in a prior commit with ci_config.json.

**Comment by neheb** [comment]
2.9.10 is the proper version

**Comment by xclaesse** [comment]
Thanks

**Pull request merged**
