### PR TITLE
update tinyxml2 to 9.0.0

### PR DESCRIPTION
**Pull request by dcbaker**
And use the upstream meson definitions instead of rolling our own.

I wrote upstream definition files to use with another project that never really took off, but since they have upstream definitions we should use those instead of our own hand rolled ones.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Nice, upstream build definitions are a definite win!

**Comment by eli-schwartz** [comment]
I think you forgot to update releases.json though :)

**Comment by eli-schwartz** [comment]
It needs to be in descending order.

**Comment by dcbaker** [comment]
And here I expected it to be in ascending order :) hopefully it's all sorted now

**Pull request merged**
