### PR TITLE
[TEST] Libffi update

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by benoit-pierre** [comment]
`closures / unwindtest_ffi_call` fails multiple times, even after increasing the timeout. I mark it as xfailed, and of course, it passes! ;(

**Comment by neheb** [comment]
mhmm. you're going to have fun with this. IIRC there are upstream bugs that need fixing.

**Comment by benoit-pierre** [comment]
> `closures / unwindtest_ffi_call` fails multiple times, even after increasing the timeout. I mark it as xfailed, and of course, it passes! ;(

Nope, I'm just an idiot…

**Comment by benoit-pierre** [comment]
Either I screwed up again, or `should_fail` has no impact on a test timeout.

**Comment by benoit-pierre** [comment]
Yes, it's your PR, with some tweaks to fix the CI.

**Comment by xclaesse** [comment]
> `closures / unwindtest_ffi_call` fails multiple times, even after increasing the timeout. I mark it as xfailed, and of course, it passes! ;(

I don't think it's a timeout, on other platforms that return immediately. Probably a deadlock. I think failing CI are upstream bugs, clang-cl is not tested and mingw32 all tests fail with autotools in upstream CI but they ignore test failure.

**Comment by benoit-pierre** [comment]
> > `closures / unwindtest_ffi_call` fails multiple times, even after increasing the timeout. I mark it as xfailed, and of course, it passes! ;(
> 
> I don't think it's a timeout, on other platforms that return immediately. Probably a deadlock. I think failing CI are upstream bugs, clang-cl is not tested and mingw32 all tests fail with autotools in upstream CI but they ignore test failure.

Yep, let's just skip that particular test.

**Pull request closed without merging**
