### PR TITLE
icu: update to 75.1

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by bgilbert** [comment]
UCRT64 failure:
```
"c++" "-Isubprojects/icu/source/common/libicuuc-75.dll.p" "-Isubprojects/icu/source/common" "-I../subprojects/icu/source/common" "-fdiagnostics-color=always" "-D_GLIBCXX_ASSERTIONS=1" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c++17" "-O0" "-g" "-DU_PLATFORM_USES_ONLY_WIN32_API" "-DWIN32" "-DWIN64" "-D_MBCS" "-D_CRT_SECURE_NO_WARNINGS" "-DWINVER=0x0601" "-D_WIN32_WINNT=0x0601" "-DU_ATTRIBUTE_DEPRECATED=" "-DU_COMMON_IMPLEMENTATION" -MD -MQ subprojects/icu/source/common/libicuuc-75.dll.p/putil.cpp.obj -MF "subprojects/icu/source/common/libicuuc-75.dll.p/putil.cpp.obj.d" -o subprojects/icu/source/common/libicuuc-75.dll.p/putil.cpp.obj "-c" ../subprojects/icu/source/common/putil.cpp
In file included from D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/cstdlib:41,
                 from D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/stdlib.h:36,
                 from ../subprojects/icu/source/common/uassert.h:23,
                 from ../subprojects/icu/source/common/putil.cpp:67:
D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/x86_64-w64-mingw32/bits/c++config.h:667:2: warning: #warning "__STRICT_ANSI__ seems to have been undefined; this is not supported" [-Wcpp]
  667 | #warning "__STRICT_ANSI__ seems to have been undefined; this is not supported"
      |  ^~~~~~~
In file included from D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/bits/chrono.h:39,
                 from D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/condition_variable:40,
                 from ../subprojects/icu/source/common/umutex.h:24,
                 from ../subprojects/icu/source/common/putil.cpp:68:
D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/limits: In static member function 'static constexpr __float128 std::numeric_limits<__float128>::min()':
D:/a/_temp/msys64/ucrt64/include/c++/14.2.0/limits:2100:30: error: unable to find numeric literal operator 'operator""Q'
 2100 |         return __extension__ 0x1.0p-16382Q;
      |                              ^~~~~~~~~~~~~
```

Looks like this was [previously reported](https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues/ICU-22002), [possibly fixed](https://github.com/unicode-org/icu/commit/86cc2b98cbf694074cfe951467cc373d26fa9df2), possibly broke again, and [fixed](https://github.com/unicode-org/icu/commit/564c92d666354a8ed0f99cba0f239eba790bd148) in the upcoming release.  Should we skip this release?

**Comment by jpakkane** [comment]
Since we can't have functional patches by policy, there's not much else we can do.

**Comment by bgilbert** [comment]
Okay, marking this as draft and leaving it open as documentation.

**Comment by bgilbert** [comment]
Closing in favor of https://github.com/mesonbuild/wrapdb/pull/1773.

**Pull request closed without merging**
