### PR TITLE
libpsl: add 0.21.2

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Comment by hrxi** [comment]
Windows compatibility of the psl tool (not required for the library) was fixed in https://github.com/rockdaboot/libpsl/pull/193, but there has been no release since then.

Does the no-patching-upstream-projects rule preclude packaging a working version of libpsl for Windows, short of a new release?

Or am I allowed to simply not compile the tool?

**Comment by neheb** [comment]
Patched meson.build files are allowed.

**Comment by neheb** [comment]
Btw localtime_r is available with MinGW. Probably better to add localtime_s support upstream though.

**Comment by hrxi** [comment]
> Probably better to add localtime_s support upstream though.

They already did that upstream, but they haven't added a new release.

**Comment by hrxi** [comment]
Works everywhere except clang-cl, I opened an issue with upstream.

**Pull request merged**
