### PR TITLE
qarchive: update to 2.2.6

### PR DESCRIPTION
**Pull request by tastytea**

### CODE REVIEW

**Comment by neheb** [comment]
@tastytea does this work? I got a bunch of unreviewed PRs merged upstream.

**Comment by tastytea** [comment]
It builds fine and the CMakeLists.txt didn't change relevantly from 2.2.4, so i assumed there are no changes necessary.

But after doing some real-world tests, i discovered that the recipe fails to add the include dir since 2.2.1-2. Changing `depinc = include_directories('.')` to `depinc = include_directories('.', 'include')` adds `-isystem../subprojects/QArchive-2.2.6/include` and solves the issue.

`../subprojects/QArchive-2.2.6` is added as include path and the header `QArchive` is in it which tries to include other headers headers in `include/`. It seems this could never work? Did it work for you?

I added the dep like this:

```meson
qarchive_dep = dependency(
  'QArchive',
  version: '>=2.0.0',
  include_type: 'system'
)
```

and ran `meson setup build --force-fallback-for=qarchive`.

**Comment by neheb** [comment]
aren't those headers only meant for inclusion by the QArchive header?

**Comment by tastytea** [comment]
Well, yeah. I include the `QArchive` header and that tries to include `qarchive_enums.hpp` but can't find it.

```
FAILED: qarchive_wrap_test.p/main.cpp.o
ccache c++ -Iqarchive_wrap_test.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++20 -O0 -g -isystem../subprojects/QArchive-2.2.6 -isystemsubprojects/QArchive-2.2.6 -MD -MQ qarchive_wrap_test.p/main.cpp.o -MF qarchive_wrap_test.p/main.cpp.o.d -o qarchive_wrap_test.p/main.cpp.o -c ../main.cpp
In file included from ../main.cpp:1:
../subprojects/QArchive-2.2.6/QArchive:36:10: fatal error: qarchive_enums.hpp: No such file or directory
   36 | #include "qarchive_enums.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

[meson-qarchive-test.tar.gz](https://github.com/mesonbuild/wrapdb/files/10561806/meson-qarchive-test.tar.gz) (simple test project, setup with `--force-fallback-for=qarchive`)

**Pull request merged**
