### PR TITLE
inih: update to r54

### PR DESCRIPTION
**Pull request by stephanlachnit**
Reported here: https://github.com/Tachi107/cloudflare-ddns/issues/10#issuecomment-1073641944

Replaces #338.

/cc @eli-schwartz

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Interesting, for some reason the Ubuntu CI builds openssl, Windows fails due to a rather odd linking error and MacOS fails from `ERROR: test_releases (__main__.TestReleases) (step='check_meson_version', name='openssl')`, which I suspect has nothing to do with inih.

**Comment by stephanlachnit** [comment]
> Another PR was merged which breaks everything. We're waiting for the submitter to fix it!

Figured, just ping me when I should rebase :)

**Comment by eli-schwartz** [comment]
Alright, time to rebase. :)

**Comment by stephanlachnit** [comment]
Rebased. The VSC linking error still persists though...
```
[1/5] Compiling C object subprojects/inih-r53/inih-0.dll.p/ini.c.obj
[2/5] Linking target subprojects/inih-r53/inih-0.dll
[3/5] Generating symbol file subprojects/inih-r53/inih-0.dll.p/inih-0.dll.symbols
[4/5] Compiling C++ object subprojects/inih-r53/INIReader-0.dll.p/cpp_INIReader.cpp.obj
[5/5] Linking target subprojects/inih-r53/INIReader-0.dll
FAILED: subprojects/inih-r53/INIReader-0.dll subprojects/inih-r53/INIReader-0.pdb 
"link"  /MACHINE:x64 /OUT:subprojects/inih-r53/INIReader-0.dll subprojects/inih-r53/INIReader-0.dll.p/cpp_INIReader.cpp.obj "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:subprojects\inih-r53\INIReader-0.pdb" "/DLL" "/IMPLIB:subprojects\inih-r53\INIReader.lib" "subprojects\inih-r53\inih.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
LINK : fatal error LNK1181: cannot open input file 'subprojects\inih-r53\inih.lib'
```

I guess this had to be the case before, I just don't quite get what the problem of the linker is. I don't see an issue in the `meson.build` wrt linking: https://github.com/benhoyt/inih/blob/r53/meson.build

I have no Windows experience, but I think `subprojects\inih-r53\inih.lib` should probably be `subprojects/inih-r53/inih-0.dll` or something - seems link a Meson/VSC bug to me?

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/FAQ.html#my-project-works-fine-on-linux-and-mingw-but-fails-to-link-with-msvc-due-to-a-missing-lib-file-fatal-error-lnk1181-why

It's a project definition bug.

**Comment by stephanlachnit** [comment]
Thanks, learned yet something again.

Can we still merge this anyway for r53? Since a half working version is still better than a non-working version.

**Comment by eli-schwartz** [comment]
I would prefer to just ask for an r54 release. :)

**Comment by stephanlachnit** [comment]
Alright, I changed this PR to r54 instead now.

**Comment by eli-schwartz** [comment]
Thanks!

**Comment by Tachi107** [comment]
Thanks everyone for the help :)

**Pull request merged**
