### PR TITLE
glfw: add version 3.3.10

### PR DESCRIPTION
**Pull request by QWERTIOX**
I don't know why it says during generation that this is still 3.3.9

### CODE REVIEW

**Comment by benoit-pierre** [comment]
> I don't know why it says during generation that this is still 3.3.9

You need to update `subprojects/packagefiles/glfw/meson.build` too.

**Comment by benoit-pierre** [comment]
And 3.4 has a number of changes to the CMake build system, you need to review those and update the meson port in `subprojects/packagefiles/glfw` accordingly.

**Comment by QWERTIOX** [comment]
thanks, by accident i also pushed commit to add 3.4 in same pr and i don't know how to remove it

**Comment by QWERTIOX** [comment]
So i need also to update libxml2?

**Comment by jpakkane** [comment]
No, it has been updated in master between you filing this MR and the test starting to run.

**Comment by QWERTIOX** [comment]
can someone run sanity checks again then?

**Comment by benoit-pierre** [comment]
Just close and re-open this PR. Or rebase and force push.

**Comment by benoit-pierre** [comment]
In any case, someone also need to approve the workflow, again, @jpakkane?

**Comment by eli-schwartz** [comment]
Please squash the commits or revert to only the first commit. :)

**Comment by benoit-pierre** [comment]
Stop, go back to a clean slate, from your current state:
```bash
# Stash your changes.
▸ git reset --soft 'c2baf80929062233d12524d88f31ab9bcc1f805d^'
▸ git stash
# Update to the original master's current head.
▸ git fetch https://github.com/mesonbuild/wrapdb.git
▸ git merge --ff --ff-only FETCH_HEAD
# Apply back your changes.
▸ git unstash
# Commit and force push.
```

**Comment by benoit-pierre** [comment]
Sorry, should be `git stash pop`, not `git unstash` (that' s my alias for it). :P

**Comment by benoit-pierre** [comment]
Did you forget to commit your changes?

**Comment by QWERTIOX** [comment]
yup, i'm tired

**Comment by benoit-pierre** [comment]
Last push is looking good :+1:.

**Comment by jpakkane** [comment]
I enabled the tests to run, but CI does not run them for some reason. :(

**Comment by jpakkane** [comment]
I'll merge this and if something breaks we can fix it afterwards.

**Comment by eli-schwartz** [comment]
I clicked the merge button about a second after you did lol

**Pull request merged**
