### PR TITLE
libliftoff: add new wrap

### PR DESCRIPTION
**Pull request by stephanlachnit**
Depends only on libdrm, which is also available as wrap.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
Looks like the meson build files have a bug: `test/libdrm_mock.h` includes `xf86drmMode.h`, which is part of libdrm, but `mock_drm_lib` has only a partial dependency on `drm` which does not include headers. To be precise
```meson
dependencies: drm.partial_dependency(compile_args: true),
```
should be
```meson
dependencies: drm.partial_dependency(compile_args: true, includes: true),
```

I will open a MR upstream.

**Comment by stephanlachnit** [comment]
Alright, here we go with another error:
```
[25/48] Compiling C object subprojects/libliftoff-v0.2.0/test/bench.p/bench.c.o
FAILED: subprojects/libliftoff-v0.2.0/test/bench.p/bench.c.o 
ccache cc -Isubprojects/libliftoff-v0.2.0/test/bench.p -Isubprojects/libliftoff-v0.2.0/test -I../subprojects/libliftoff-v0.2.0/test -I../subprojects/libliftoff-v0.2.0/include -Isubprojects/libdrm-2.4.111 -I../subprojects/libdrm-2.4.111 -I../subprojects/libdrm-2.4.111/include/drm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c99 -O0 -g -Wundef -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-unused-parameter -MD -MQ subprojects/libliftoff-v0.2.0/test/bench.p/bench.c.o -MF subprojects/libliftoff-v0.2.0/test/bench.p/bench.c.o.d -o subprojects/libliftoff-v0.2.0/test/bench.p/bench.c.o -c ../subprojects/libliftoff-v0.2.0/test/bench.c
In file included from ../subprojects/libdrm-2.4.111/include/drm/drm.h:948,
                 from ../subprojects/libdrm-2.4.111/xf86drmMode.h:43,
                 from ../subprojects/libliftoff-v0.2.0/include/libliftoff.h:8,
                 from ../subprojects/libliftoff-v0.2.0/test/bench.c:3:
../subprojects/libdrm-2.4.111/include/drm/drm_mode.h:819:10: error: ISO C99 doesn’t support unnamed structs/unions [-Werror=pedantic]
  819 |         };
      |          ^
cc1: all warnings being treated as errors
```
So I changed:
```meson
mock_liftoff = declare_dependency(
	link_with: [mock_drm_lib, liftoff_lib],
	include_directories: [liftoff_inc],
	dependencies: drm.partial_dependency(compile_args: true),
```
to:
```meson
mock_liftoff = declare_dependency(
	link_with: mock_drm_lib,
	dependencies: [liftoff, drm.partial_dependency(compile_args: true)],
)
```
which solves all warnings except for one:
```
[78/110] Compiling C object subprojects/libliftoff-v0.2.0/test/libdrm.so.2.p/libdrm_mock.c.o
FAILED: subprojects/libliftoff-v0.2.0/test/libdrm.so.2.p/libdrm_mock.c.o 
ccache cc -Isubprojects/libliftoff-v0.2.0/test/libdrm.so.2.p -Isubprojects/libliftoff-v0.2.0/test -I../subprojects/libliftoff-v0.2.0/test -Isubprojects/libdrm-2.4.111 -I../subprojects/libdrm-2.4.111 -I../subprojects/libdrm-2.4.111/include/drm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c99 -O0 -g -Wundef -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-unused-parameter -fPIC -MD -MQ subprojects/libliftoff-v0.2.0/test/libdrm.so.2.p/libdrm_mock.c.o -MF subprojects/libliftoff-v0.2.0/test/libdrm.so.2.p/libdrm_mock.c.o.d -o subprojects/libliftoff-v0.2.0/test/libdrm.so.2.p/libdrm_mock.c.o -c ../subprojects/libliftoff-v0.2.0/test/libdrm_mock.c
In file included from ../subprojects/libdrm-2.4.111/include/drm/drm.h:948,
                 from ../subprojects/libdrm-2.4.111/xf86drmMode.h:43,
                 from ../subprojects/libliftoff-v0.2.0/test/libdrm_mock.h:6,
                 from ../subprojects/libliftoff-v0.2.0/test/libdrm_mock.c:10:
../subprojects/libdrm-2.4.111/include/drm/drm_mode.h:819:10: error: ISO C99 doesn’t support unnamed structs/unions [-Werror=pedantic]
  819 |         };
      |          ^
cc1: all warnings being treated as errors
```
I did get rid of the warning when replacing
```meson
dependencies: drm.partial_dependency(compile_args: true),
```
with
```meson
dependencies: drm,
```
But I guess this defeats the purpose of this mock library. Any clues?

**Comment by dcbaker** [comment]
Turn off werror by default upstream.

**Comment by stephanlachnit** [comment]
> Turn off werror by default upstream.

I don't think this solves the underlying issue here.

I've looked into it, and I think it is actually a libdrm bug. They specify C99, while they should specify C11 for unnamed structs. It would also make sense for libliftoff to specify C11 as well.

**Comment by dcbaker** [comment]
If you open an issue upstream you can mention me there (dbaker on fdo), though I don’t know if anyone will care too much about -pedantic warnings.

**Comment by emersion** [comment]
Hm, ideally libdrm would be included with `-isystem`, so that their headers don't cause warnings. Maybe try adding `include_type: 'system'` to the libdrm dep?

> Turn off werror by default upstream.

NACK, this is an important feature I'm not willing to give up.

**Comment by stephanlachnit** [comment]
> Hm, ideally libdrm would be included with -isystem, so that their headers don't cause warnings. Maybe try adding include_type: 'system' to the libdrm dep?

Unfortunately this is not possible with a partial dep, and the drm dep itself  already specifies `include_type: 'system'`.

Anyway, this is fixed by switching to C11 for libdrm / libliftoff.

**Comment by stephanlachnit** [comment]
Fixed upstream, needs to wait for a new release though as I don't think we can add diff files here (or can we?)

**Comment by jpakkane** [comment]
No by design. Only build system changes are allowed.

**Comment by stephanlachnit** [comment]
> No by design. Only build system changes are allowed.

I mean it is a fixup for the upstream meson build system, so I guess this hasn't happened before. But I understand it.

**Comment by tristan957** [comment]
> NACK, this is an important feature I'm not willing to give up.

`werror` is only useful in CI, so your default branch always compiles without error given a reproducible environment. `werror` by default is just a pain for developers trying to get work done. If my compiler isn't the same as yours, the warnings can be totally different.

**Comment by emersion** [comment]
> werror by default is just a pain for developers

No, warnings indicate things which needs fixing. Trigger-happy warnings are disabled.

> If my compiler isn't the same as yours, the warnings can be totally different.

This is by design: this encourages developers to submit fixes for warnings which are triggered on their system. Has worked pretty well so far for wlroots.

Anyways, not a really on-topic discussion here.

**Comment by stephanlachnit** [comment]
> No, warnings indicate things which needs fixing. Trigger-happy warnings are disabled.

+1, else the cstd issue wouldn't have been found

**Comment by stephanlachnit** [comment]
Anyway, updated to 0.3.0, good to merge now @eli-schwartz

**Comment by eli-schwartz** [comment]
> `werror` by default is just a pain for developers trying to get work done. If my compiler isn't the same as yours, the warnings can be totally different.

I'm not convinced that Werror is bad for developers of any variety.

What it is bad for is people building releases for e.g. distros, as they aren't in a position to submit fixes and wait a while for a new stable tag before updating packages.

... But that's why Meson standardizes on how to disable Werror without patching build files.

**Comment by emersion** [comment]
> What it is bad for is people building releases for e.g. distros, as they aren't in a position to submit fixes and wait a while for a new stable tag before updating packages.

Yup, completely agree. We have a document explaining best practices for distros here: https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/Packaging-recommendations

I wonder if some of it could be upstreamed in some way in the Meson docs?

**Pull request merged**
