### PR TITLE
flatbuffers: update to 23.1.21

### PR DESCRIPTION
**Pull request by jmillan**

### CODE REVIEW

**Comment by jmillan** [comment]
> why remove patch_directory = flatbuffers ?

Oh, that was unintentioal.

**Comment by jmillan** [comment]
Fixed.

**Comment by eli-schwartz** [comment]
In the future, please use `git commit --amend` and force push -- do NOT delete something in one commit and add it back in another commit, that results in very messy commit logs... :)

(We should not be merging it like that, IMO.)

**Comment by jmillan** [comment]
> In the future, please use git commit --amend and force push

Ok, I will :+1:

**Pull request merged**
