### PR TITLE
Add range-v3 provide section in the wrap file.

### PR DESCRIPTION
**Pull request by B4mbus**
Added a provide section for the range-v3 wrap file and dependency name in the releases file.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Thanks, but in order to trigger a new release you will need to bump the version in `releases.json` as well.

(The part after the `-` is the wrapdb build number added on to the upstream stable tag.)

**Comment by eli-schwartz** [comment]
Actually now might be a good time to bump it to the upstream 0.11.0 stable tag. You can do that in a second commit.

**Comment by B4mbus** [comment]
@eli-schwartz it is done now. Please tell me know if I made any mistake or need to change something again, thanks.

**Comment by eli-schwartz** [comment]
Perfect, thanks!

**Pull request merged**
