### PR TITLE
unit-system: update to 0.5.3

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
I could probably fix this with a def fine. No idea how C++ functions are named though...

**Comment by jpakkane** [comment]
In Debian at least it is possible to give C++ function names in unmangled form. If VS does not support that then the only reasonable way to make it work is with visibility attributes.

**Comment by neheb** [comment]
a git grep of build_target indicates that this is just avoided by compiling static on MSVC.

**Comment by neheb** [comment]
ping @noah1510 since you're active here, can you add dllexport to this package?

**Comment by noah1510** [comment]
I copied the dllexport include from the imgui package into the latest commit. This should get it working right? If so I will create a new patch release.

**Comment by neheb** [comment]
```
 LINK : warning LNK4001: no object files specified; libraries used
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
subprojects\unit-system-0.5.3\generic\unit-system-generic-0.dll : fatal error LNK1120: 1 unresolved externals
```

No idea what's going on.

**Comment by jpakkane** [comment]
The upstream build definition specifies a library file that has no sources, only headers. If this is a header-only library then it should not try to build a library, the `declare_dependency` only needs an `include_directories` in that case.

**Comment by noah1510** [comment]
@jpakkane Thanks for the advice. Now the static compile works on windows.

Is there a way to automatically generate the def files? As long as there is none and I would have to add export macros to all of the functions of the headers, I will **not** support msvc if that is the case.

**Comment by xclaesse** [comment]
Why is this adding a meson.build file? Upstream has one: https://github.com/noah1510/unit-system/blob/main/meson.build

**Comment by neheb** [comment]
Intermediate step to trying to figure out MSVC compilation.

**Comment by neheb** [comment]
> @jpakkane Thanks for the advice. Now the static compile works on windows.
> 
> Is there a way to automatically generate the def files? As long as there is none and I would have to add export macros to all of the functions of the headers, I will **not** support msvc if that is the case.

You can create a python script to do this. See https://github.com/libsndfile/libsndfile/blob/master/src/create_symbols_file.py

**Comment by noah1510** [comment]
That would in theory be an option.
However for this library its kind of overkill since every symbol need to be exported.
To not miss a symbol I would automatically generate the symbol list from the linux so files and pray the list does not break anything.

Does the order of the symbols matter or is it fine if they are in whatever order they are in a so file by default?

**Comment by noah1510** [comment]
I just uploaded a first set of def files to the git repo. Since I have no windows machine to test on right now, I can not integrate them into the build system files yet. Tomorrow I should get them working if everything goes according to plan.

**Comment by noah1510** [comment]
I added the def files for the core modules. Now the shared compile works with msvc as long as the tests are disabled.

**Comment by neheb** [comment]
```
2022-09-01T21:23:19.1822355Z [16/20] "link"  /MACHINE:x64 /OUT:subprojects/unit-system-0.5.3/generic/unit-system-generic-0.dll  "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:subprojects\unit-system-0.5.3\generic\unit-system-generic-0.pdb" "/DLL" "/IMPLIB:subprojects\unit-system-0.5.3\generic\unit-system-generic.lib" "/MAP" "/MAPINFO:EXPORTS" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
2022-09-01T21:23:19.1824985Z FAILED: subprojects/unit-system-0.5.3/generic/unit-system-generic-0.dll subprojects/unit-system-0.5.3/generic/unit-system-generic-0.pdb 
2022-09-01T21:23:19.1827163Z "link"  /MACHINE:x64 /OUT:subprojects/unit-system-0.5.3/generic/unit-system-generic-0.dll  "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:subprojects\unit-system-0.5.3\generic\unit-system-generic-0.pdb" "/DLL" "/IMPLIB:subprojects\unit-system-0.5.3\generic\unit-system-generic.lib" "/MAP" "/MAPINFO:EXPORTS" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
2022-09-01T21:23:19.1829089Z LINK : warning LNK4001: no object files specified; libraries used
2022-09-01T21:23:19.1829669Z LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
2022-09-01T21:23:19.1830476Z subprojects\unit-system-0.5.3\generic\unit-system-generic-0.dll : fatal error LNK1120: 1 unresolved externals
2022-09-01T21:23:19.1831194Z ninja: build stopped: subcommand failed.
```

@noah1510

**Comment by neheb** [comment]
Never mind. Builds after adding another file. Waiting for new release so I can get rid of all of these files.

**Pull request merged**
