### PR TITLE
fluidsynth: fix error when `sh` is not available

### PR DESCRIPTION
**Pull request by benoit-pierre**
The setup step would abort with `ERROR: Program or command 'sh' not found or not executable`.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I guess the CI runner happened to have it installed, lol...

Thanks for catching that.

**Comment by benoit-pierre** [comment]
It's the `run_command('sh', …)` invocation that fails if there's no `sh` executable available.

**Comment by benoit-pierre** [comment]
There does not seem to be a point in using `disabler: true` in this case.

**Comment by benoit-pierre** [comment]
Also, it might make more sense for the run command to actually use `shell_cmd`, no?

**Comment by eli-schwartz** [comment]
Aha...

The run_command should be running shell_cmd instead of `'sh'` so that it reuses the found program object rather than creating an implicit second one. This will also prevent meson from logging twice that it tries to find that program.

**Comment by benoit-pierre** [comment]
Ah, yes, it should be:
```python
  shell_cmd = find_program('sh', required : false, disabler: true)
  host_is_msys2 = run_command(shell_cmd, '-c', '[ ! -z "$MSYSTEM" ] && [ "$MSYSTEM" != "MSYS" ] && exit 0; exit 1', check: false).returncode() == 0
```

**Comment by benoit-pierre** [comment]
Will amend.

**Comment by benoit-pierre** [comment]
Done.

**Comment by benoit-pierre** [comment]
It's [fixed upstream](https://gitlab.gnome.org/GNOME/glib/-/commit/e5dc299701df7189685d322cb709649ce3c9c81d), but not released yet, would that be an accepted exception to the `it is generally not accepted to override upstream files` rule?

**Comment by eli-schwartz** [comment]
That's fixed on the glib maintenance branch which is scheduled for release at the beginning of December.

Actually, that release will also include a thing to make it use the same wrap name as the wrapdb itself -- which means that meson can prioritize using the wrapdb copy which we can independently fix the url for.

**Comment by benoit-pierre** [comment]
OK.

**Comment by eli-schwartz** [comment]
Actually I can just merge this with failing CI, as the change is verifiably correct via eyeball review.

**Comment by benoit-pierre** [comment]
Well, that part does work as expected yes (I'm hitting other issues).

**Pull request merged**
