### PR TITLE
libupnp: update to 1.14.19

### PR DESCRIPTION
**Pull request by neheb**
Use some loops instead of set10.

### CODE REVIEW

**Comment by neheb** [comment]
Ok so arm64 CI is using

```
/opt/homebrew/bin/pkg-config)
```

and the x86 one is using

```
/usr/local/bin/pkg-config
```

is the latter missing on arm64?

**Comment by neheb** [comment]
ping @benoit-pierre 

x86 is using system openssl and arm64 is using broken homebrew openssl...

**Comment by benoit-pierre** [comment]
Yep, since #1492 was merged without the fix. Which I assume was the intent, option 2: ignore the error on macOS amd64, no?

**Comment by neheb** [comment]
Yeah. I'm just curious why the difference.

**Comment by benoit-pierre** [comment]
What difference?

**Comment by neheb** [comment]
the different pkg-config binaries. The /opt one seems to prefer homebrew packages that are keg-only.

**Pull request merged**
