### PR TITLE
Add wrap files for Kraken-Engine-0.0.1

### PR DESCRIPTION
**Pull request by durkisneer1**

### CODE REVIEW

**Comment by durkisneer1** [comment]
I've been forgotten 😔

**Comment by jpakkane** [comment]
You need to rebase against current master to make the error go away.

**Comment by durkisneer1** [comment]
Got it, thanks. There were no errors with the sanity checks on my local system with VS and MingW so hopefully the next workflow pass doesn't also fail.

**Comment by jpakkane** [comment]
You used a merge. Those are not allowed because they screw up history. Convert it to a rebase instead. Thanks.

**Pull request closed without merging**
