### PR TITLE
flac: fix compilation on non x86 and clang

### PR DESCRIPTION
**Pull request by neheb**
clang's cpuid header errors with "this header is for x86 only". Make it
conditional.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
the flac code also only uses __cpuid for x86. ping @jpakkane

**Comment by dcbaker** [comment]
Use check _header instead of has_header, which will catch this

**Comment by dcbaker** [comment]
Actually, this sort is bs is exactly why check_header exists :/

**Comment by neheb** [comment]
sounds like has_header should be deprecated.

**Comment by dcbaker** [comment]
Has_header is faster, but I never use it because iof this concern. We should at least have a big warning in the docs about it

**Comment by neheb** [comment]
```
~/d/wrapdb (master)> git grep "\.check_header"
subprojects/packagefiles/cmocka/meson.build:    if compiler.check_header(h)
subprojects/packagefiles/sdl2/meson.build:    if cc.check_header(h, dependencies : core_deps)
```

not widely used it seems.

**Comment by dcbaker** [comment]
I’m honestly tempted to add a check keyword to has_header that defaults to false and note that in the future it will change to true

**Comment by neheb** [comment]
ping @jpakkane

**Pull request merged**
