### PR TITLE
glib-networking: add 2.78.0

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Comment by hrxi** [comment]
This fails with
```
======================================================================
FAIL: test_releases (__main__.TestReleases) (step='provide', name='glib-networking')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\wrapdb\wrapdb\tools\sanity_checks.py", line 224, in test_releases
    self.assertIn('provide', config.sections())
AssertionError: 'provide' not found in ['wrap-file']
```

However, it is kind of by design that this wrap doesn't provide any libraries to link to. glib-networking creates/installs gio plugins that allow gio to make TLS connections. You don't directly depend on that.

**Comment by xclaesse** [comment]
I would add a new flag in ci_config.json that tells this wrap is not providing anything.

**Comment by benoit-pierre** [comment]
There's a dirty workaround: you can add an empty `dependency_names =` or `program_names =` line to the provide section. Example:
```yml
[provide]
program_names =
```
:P

**Comment by benoit-pierre** [comment]
Why even add yet another key to `ci_config.json`? `sanity_check.py` should allow a `release.json` entry with no `dependency_names` / `program_names`.

**Comment by hrxi** [comment]
> Why even add yet another key to `ci_config.json`? `sanity_check.py` should allow a `release.json` entry with no `dependency_names` / `program_names`.

I have no opinion on this. If you come to a conclusion of what to do, I'll do it.

**Comment by benoit-pierre** [comment]
[This step](https://github.com/mesonbuild/wrapdb/blob/master/tools/sanity_checks.py#L236) checks that the list of provides in `release.json` and the wrap are the same, so IMHO [that step](https://github.com/mesonbuild/wrapdb/blob/master/tools/sanity_checks.py#L222) can just be removed.

**Comment by xclaesse** [comment]
> Why even add yet another key to `ci_config.json`? `sanity_check.py` should allow a `release.json` entry with no `dependency_names` / `program_names`.

Originally that was because it's a common mistake to forget listing dependencies a wrap provide. A new contributor and uncareful reviewer could omit dependency names in both [provide] section and releases.json. But maybe we should just assume we'll review carefully...

**Comment by hrxi** [comment]
CC #1017

**Pull request merged**
