### PR TITLE
libsndfile: add sndio_dep to sndfile-play

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation when found. Matches CMakeLists.txt.

Ran through muon's fmt.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

ping @alex-tee

### CODE REVIEW

**Comment by alex-tee** [comment]
this is still broken for me:

```
ninja: Entering directory `build'
[9/2336] Generating subprojects/gtk4/gdk/gdkmarshalers_h with a custom command
INFO: Reading ../subprojects/gtk4/gdk/gdkmarshalers.list...
[19/2336] Compiling C object subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o
FAILED: subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o 
cc -Isubprojects/libsndfile-1.1.0/programs/sndfile-play.p -Isubprojects/libsndfile-1.1.0/programs -I../subprojects/libsndfile-1.1.0/programs -Isubprojects/libsndfile-1.1.0 -I../subprojects/libsndfile-1.1.0 -I../subprojects/libsndfile-1.1.0/src -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -g -MD -MQ subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o -MF subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o.d -o subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o -c ../subprojects/libsndfile-1.1.0/programs/sndfile-play.c
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c: In function 'sndio_play':
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:677:25: error: storage size of 'par' isn't known
  677 |         struct sio_par  par ;
      |                         ^~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:28: warning: implicit declaration of function 'sio_open'; did you mean 'sf_open'? [-Wimplicit-function-declaration]
  695 |                 if ((hdl = sio_open (NULL, SIO_PLAY, 0)) == NULL)
      |                            ^~~~~~~~
      |                            sf_open
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:44: error: 'SIO_PLAY' undeclared (first use in this function)
  695 |                 if ((hdl = sio_open (NULL, SIO_PLAY, 0)) == NULL)
      |                                            ^~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:44: note: each undeclared identifier is reported only once for each function it appears in
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:700:17: warning: implicit declaration of function 'sio_initpar' [-Wimplicit-function-declaration]
  700 |                 sio_initpar (&par) ;
      |                 ^~~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:705:26: error: 'SIO_LE_NATIVE' undeclared (first use in this function)
  705 |                 par.le = SIO_LE_NATIVE ;
      |                          ^~~~~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:707:23: warning: implicit declaration of function 'sio_setpar' [-Wimplicit-function-declaration]
  707 |                 if (! sio_setpar (hdl, &par) || ! sio_getpar (hdl, &par))
      |                       ^~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:707:51: warning: implicit declaration of function 'sio_getpar' [-Wimplicit-function-declaration]
  707 |                 if (! sio_setpar (hdl, &par) || ! sio_getpar (hdl, &par))
      |                                                   ^~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:712:23: warning: implicit declaration of function 'sio_start'; did you mean 'va_start'? [-Wimplicit-function-declaration]
  712 |                 if (! sio_start (hdl))
      |                       ^~~~~~~~~
      |                       va_start
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:718:25: warning: implicit declaration of function 'sio_write' [-Wimplicit-function-declaration]
  718 |                         sio_write (hdl, buffer, readcount * sizeof (short)) ;
      |                         ^~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:720:17: warning: implicit declaration of function 'sio_close'; did you mean 'sf_close'? [-Wimplicit-function-declaration]
  720 |                 sio_close (hdl) ;
      |                 ^~~~~~~~~
      |                 sf_close
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:677:25: warning: unused variable 'par' [-Wunused-variable]
  677 |         struct sio_par  par ;
      |                         ^~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c: At top level:
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:675:1: warning: 'sndio_play' defined but not used [-Wunused-function]
  675 | sndio_play (int argc, char *argv [])
      | ^~~~~~~~~~
[37/2336] Generating subprojects/gtk4/gdk/gdkmarshalers_c with a custom command
INFO: Reading ../subprojects/gtk4/gdk/gdkmarshalers.list...
[41/2336] Generating subprojects/libaudec/config.h with a custom command
fatal: No annotated tags can describe '46f5aa04316f94bfbfa90d6b3514df54e90f0602'.
However, there were unannotated tags: try --tags.
[44/2336] Generating subprojects/pango-1.50.6/pango/pango-enum-types.h with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.
```

I copied subprojects/packagefiles/libsndfile and subprojects/libsndfile.wrap to my project and configured/built

**Comment by neheb** [comment]
what OS is this?

**Comment by alex-tee** [comment]
vanilla Arch Linux

**Comment by neheb** [comment]
@alex-tee restricted to openbsd. Please retest.

**Comment by alex-tee** [comment]
```
Executing subproject libsndfile 

libsndfile| Project name: libsndfile
libsndfile| Project version: 1.1.0
libsndfile| C compiler for the host machine: cc (gcc 12.1.1 "cc (GCC) 12.1.1 20220730")
libsndfile| C linker for the host machine: cc ld.bfd 2.39
libsndfile| Library m found: YES
libsndfile| Run-time dependency libmpg123 found: YES 1.30.2
libsndfile| Library mp3lame found: YES
libsndfile| Run-time dependency ogg found: YES 1.3.5
libsndfile| Run-time dependency flac found: YES 1.3.4
libsndfile| Run-time dependency vorbis found: YES 1.3.7
libsndfile| Run-time dependency vorbisenc found: YES 1.3.7
libsndfile| Run-time dependency opus found: YES 1.3.1
libsndfile| Run-time dependency sndio found: YES 1.9.0
libsndfile| Header "sys/stat.h" has symbol "S_IRGRP" : YES
libsndfile| Header "sys/types.h" has symbol "ssize_t" : YES
libsndfile| Checking for function "calloc" : YES
libsndfile| Checking for function "ceil" : YES
libsndfile| Checking for function "floor" : YES
libsndfile| Checking for function "fmod" : YES
libsndfile| Checking for function "free" : YES
libsndfile| Checking for function "fstat" : YES
libsndfile| Checking for function "fstat64" : YES
libsndfile| Checking for function "fsync" : YES
libsndfile| Checking for function "ftruncate" : YES
libsndfile| Checking for function "getpagesize" : YES
libsndfile| Checking for function "gettimeofday" : YES
libsndfile| Checking for function "gmtime" : YES
libsndfile| Checking for function "localtime" : YES
libsndfile| Checking for function "lrint" : YES
libsndfile| Checking for function "lrintf" : YES
libsndfile| Checking for function "lround" : YES
libsndfile| Checking for function "lseek" : YES
libsndfile| Checking for function "lseek64" : YES
libsndfile| Checking for function "malloc" : YES
libsndfile| Checking for function "mmap" : YES
libsndfile| Checking for function "open" : YES
libsndfile| Checking for function "pipe" : YES
libsndfile| Checking for function "read" : YES
libsndfile| Checking for function "realloc" : YES
libsndfile| Checking for function "setlocale" : YES
libsndfile| Checking for function "snprintf" : YES
libsndfile| Checking for function "vsnprintf" : YES
libsndfile| Checking for function "waitpid" : YES
libsndfile| Checking for function "write" : YES
libsndfile| Checking for function "gmtime_r" : YES
libsndfile| Checking for function "localtime_r" : YES (cached)
libsndfile| Has header "alsa/asoundlib.h" : YES
libsndfile| Has header "byteswap.h" : YES
libsndfile| Has header "dlfcn.h" : YES
libsndfile| Has header "endian.h" : YES
libsndfile| Has header "immintrin.h" : YES
libsndfile| Has header "inttypes.h" : YES
libsndfile| Has header "locale.h" : YES
libsndfile| Has header "memory.h" : YES
libsndfile| Has header "stdbool.h" : YES
libsndfile| Has header "stdint.h" : YES
libsndfile| Has header "stdlib.h" : YES
libsndfile| Has header "strings.h" : YES
libsndfile| Has header "string.h" : YES
libsndfile| Has header "sys/stat.h" : YES
libsndfile| Has header "sys/time.h" : YES (cached)
libsndfile| Has header "sys/types.h" : YES
libsndfile| Has header "sys/wait.h" : YES
libsndfile| Has header "unistd.h" : YES (cached)
libsndfile| Checking for size of "int64_t" : 8
libsndfile| Checking for size of "long" : 8
libsndfile| Checking for size of "long long" : 8
libsndfile| Checking for size of "off_t" : 8
libsndfile| Checking for size of "ssize_t" : 8
libsndfile| Checking for size of "wchar_t" : 4
libsndfile| Checking for size of "double" : 8
libsndfile| Checking for size of "float" : 4
libsndfile| Checking for size of "int" : 4
libsndfile| Checking for size of "loff_t" : -1
libsndfile| Checking for size of "off64_t" : -1
libsndfile| Checking for size of "short" : 2
libsndfile| Checking for size of "size_t" : 8
libsndfile| Configuring config.h using configuration
libsndfile| Configuring sndfile.h using configuration
libsndfile| Checking if "-Wl,--version-script" : links: NO
libsndfile| Run-time dependency alsa found: YES 1.2.7.2
libsndfile| Build targets in project: 12
libsndfile| Subproject libsndfile finished.

Dependency sndfile from subproject subprojects/libsndfile-1.1.0 found: YES 1.1.0
```

then

```
[36/2334] Compiling C object subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o
FAILED: subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o 
cc -Isubprojects/libsndfile-1.1.0/programs/sndfile-play.p -Isubprojects/libsndfile-1.1.0/programs -I../subprojects/libsndfile-1.1.0/programs -Isubprojects/libsndfile-1.1.0 -I../subprojects/libsndfile-1.1.0 -I../subprojects/libsndfile-1.1.0/src -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -g -MD -MQ subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o -MF subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o.d -o subprojects/libsndfile-1.1.0/programs/sndfile-play.p/sndfile-play.c.o -c ../subprojects/libsndfile-1.1.0/programs/sndfile-play.c
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c: In function 'sndio_play':
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:677:25: error: storage size of 'par' isn't known
  677 |         struct sio_par  par ;
      |                         ^~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:28: warning: implicit declaration of function 'sio_open'; did you mean 'sf_open'? [-Wimplicit-function-declaration]
  695 |                 if ((hdl = sio_open (NULL, SIO_PLAY, 0)) == NULL)
      |                            ^~~~~~~~
      |                            sf_open
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:44: error: 'SIO_PLAY' undeclared (first use in this function)
  695 |                 if ((hdl = sio_open (NULL, SIO_PLAY, 0)) == NULL)
      |                                            ^~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:695:44: note: each undeclared identifier is reported only once for each function it appears in
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:700:17: warning: implicit declaration of function 'sio_initpar' [-Wimplicit-function-declaration]
  700 |                 sio_initpar (&par) ;
      |                 ^~~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:705:26: error: 'SIO_LE_NATIVE' undeclared (first use in this function)
  705 |                 par.le = SIO_LE_NATIVE ;
      |                          ^~~~~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:707:23: warning: implicit declaration of function 'sio_setpar' [-Wimplicit-function-declaration]
  707 |                 if (! sio_setpar (hdl, &par) || ! sio_getpar (hdl, &par))
      |                       ^~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:707:51: warning: implicit declaration of function 'sio_getpar' [-Wimplicit-function-declaration]
  707 |                 if (! sio_setpar (hdl, &par) || ! sio_getpar (hdl, &par))
      |                                                   ^~~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:712:23: warning: implicit declaration of function 'sio_start'; did you mean 'va_start'? [-Wimplicit-function-declaration]
  712 |                 if (! sio_start (hdl))
      |                       ^~~~~~~~~
      |                       va_start
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:718:25: warning: implicit declaration of function 'sio_write' [-Wimplicit-function-declaration]
  718 |                         sio_write (hdl, buffer, readcount * sizeof (short)) ;
      |                         ^~~~~~~~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:720:17: warning: implicit declaration of function 'sio_close'; did you mean 'sf_close'? [-Wimplicit-function-declaration]
  720 |                 sio_close (hdl) ;
      |                 ^~~~~~~~~
      |                 sf_close
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:677:25: warning: unused variable 'par' [-Wunused-variable]
  677 |         struct sio_par  par ;
      |                         ^~~
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c: At top level:
../subprojects/libsndfile-1.1.0/programs/sndfile-play.c:675:1: warning: 'sndio_play' defined but not used [-Wunused-function]
  675 | sndio_play (int argc, char *argv [])
      | ^~~~~~~~~~
```

**Comment by neheb** [comment]
I can't duplicate your failures. Make sure you're cleaning the libsndfile-1.1.0 directory/modifying the meson.build file.

**Comment by neheb** [comment]
With an arch linux container I reproduced this. However, once I applied this PR it compiles fine.

**Comment by alex-tee** [comment]
it looks like there was a cache in subprojects/packagecache. after deleting that and trying again it builds and runs without issues @neheb

**Pull request merged**
