### PR TITLE
harfbuzz: update to 9.0.0

### PR DESCRIPTION
**Pull request by benoit-pierre**

### CODE REVIEW

**Comment by benoit-pierre** [comment]
A lot of failures… o.O

@eli-schwartz @jpakkane : [this one look like a meson issue](https://github.com/mesonbuild/wrapdb/actions/runs/9704282622/job/26784209517?pr=1569#step:6:646).

**Comment by neheb** [comment]
msys2 failures may be fixable with installing the icu package.

**Comment by benoit-pierre** [comment]
And for VisualStudio (x86)? We have `python-packaging` in `msys_packages`, but since we're setting up a custom python…

**Comment by benoit-pierre** [comment]
OK, so:
- VisualStudio jobs: latest meson pre-release (1.5.0rc2) is still borked
- MSYS2 (CLANG64): a GLib issue (should be [fixed](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4125) in the next release)

**Comment by benoit-pierre** [comment]
And why is are the downloads so slow on the VisualStudio jobs?
- VisualStudio (x64):
```
Fri, 05 Jul 2024 12:05:58 GMT Downloading harfbuzz source from https://github.com/harfbuzz/harfbuzz/releases/download/9.0.0/harfbuzz-9.0.0.tar.xz
Fri, 05 Jul 2024 12:07:04 GMT
Fri, 05 Jul 2024 12:07:04 GMT Executing subproject harfbuzz
```
- VisualStudio (x86):
```
Fri, 05 Jul 2024 12:06:06 GMT Downloading harfbuzz source from https://github.com/harfbuzz/harfbuzz/releases/download/9.0.0/harfbuzz-9.0.0.tar.xz
Fri, 05 Jul 2024 12:06:58 GMT
Fri, 05 Jul 2024 12:06:58 GMT Executing subproject harfbuzz
```
- VisualStudio-clang-cl:
```
Fri, 05 Jul 2024 12:05:42 GMT Downloading harfbuzz source from https://github.com/harfbuzz/harfbuzz/releases/download/9.0.0/harfbuzz-9.0.0.tar.xz
Fri, 05 Jul 2024 12:06:41 GMT
Fri, 05 Jul 2024 12:06:41 GMT Executing subproject harfbuzz
```

**Comment by benoit-pierre** [comment]
@neheb: this can be merged, the remaining issues are with meson and glib.

**Pull request merged**
