### PR TITLE
pango: add 1.51.0

### PR DESCRIPTION
**Pull request by hrxi**

### CODE REVIEW

**Comment by xclaesse** [comment]
I'm not sure about version convention in pango, is 1.51 stable release?

**Comment by hrxi** [comment]
> I'm not sure about version convention in pango

Me neither.

> is 1.51 stable release?

I couldn't find anything to the contrary on their website: https://pango.gnome.org/.

**Comment by hrxi** [comment]
```
../subprojects/pixman-0.42.2/pixman/pixman-mmx.c(247,8): error: member reference base type '__m64' (vector of 1 'long long' value) is not a structure or union
    res.M64_MEMBER = x;
    ~~~^~~~~~~~~~~
../subprojects/pixman-0.42.2/pixman/pixman-mmx.c(262,21): error: member reference base type '__m64' (vector of 1 'long long' value) is not a structure or union
    uint64_t res = x.M64_MEMBER;
                   ~^~~~~~~~~~~
```

Ideas? Seems to be caused by the pixman wrap, not pango. Can I somehow skip running on clang-cl?

**Comment by neheb** [comment]
@hrxi upstream has known about the issue for 3 years. Nothing has been done. Just ignore it.

**Comment by hrxi** [comment]
> @hrxi upstream has known about the issue for 3 years. Nothing has been done.

Can you link the issue, just for future reference? Wasn't able to find it quickly (or even the bug tracker).

> Just ignore it.

How do I ignore it for VS-clang-cl only?

**Comment by hrxi** [comment]
Ah, found it: https://gitlab.freedesktop.org/pixman/pixman/-/issues/41.

**Comment by neheb** [comment]
can't ignore just clang-cl. at least not yet. wouldn't really work either. has to fail at configure it order for it to work. I'd just ignore the failure.

**Comment by hrxi** [comment]
> I'd just ignore the failure.

How do I do this? What key do I have to use in `ci_config.json`? Or should I adjust the tools/sanity_check.py script?

**Pull request merged**
