### PR TITLE
glfw: add version 3.4

### PR DESCRIPTION
**Pull request by QWERTIOX**
There are some changes needed in port because sanity checks don't pass

### CODE REVIEW

**Comment by QWERTIOX** [comment]
Ok, why sanity checks here gives useful information and mine is spamed with garbage

**Comment by eli-schwartz** [comment]
Your sanity checks were run where? Locally? In your fork's Actions runners?

**Comment by QWERTIOX** [comment]
Locally

**Comment by QWERTIOX** [comment]
@neheb maybe you can help, i saw that you were last person to update the patch?

**Comment by QWERTIOX** [comment]
i don't know how to do it :/

**Pull request closed without merging**
