### PR TITLE
workflows: install pkgconfiglite for Windows

### PR DESCRIPTION
**Pull request by neheb**
Prevents packages marked false for windows from failing.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by xclaesse** [comment]
What does this fix exactly?

**Comment by neheb** [comment]
Fixes this from throwing on Windows builds: https://github.com/mesonbuild/wrapdb/blob/master/tools/sanity_checks.py#L339

**Comment by xclaesse** [comment]
Can you elaborate a bit how it fixes that? I fail to understand why pkg-config is needed on Windows at all, it will never find any dependency, does it?

**Comment by neheb** [comment]
Example of such a failure: https://github.com/mesonbuild/wrapdb/actions/runs/3178610216/jobs/5180284621

**Comment by xclaesse** [comment]
```
    "_comment": "libmicrohttpd and libcurl are not available with MSVC CI",
    "build_on": {
      "windows": false
    }
```

It is expected to not build on Windows, installing pkgconfiglite should not make any difference. If it does make a difference that's a bug we should investigate the root cause.

**Comment by xclaesse** [comment]
Pretty sure that's another issue with https://github.com/mesonbuild/wrapdb/pull/631, Meson is right in failing with `ERROR: Pkg-config binary for machine 1 not found. Giving up.` but that PR does not parse correctly such error message.

@eli-schwartz could you check that please?
@neheb could you remove the couple `pkgconfiglite` you added into ci_config.json already?

**Comment by eli-schwartz** [comment]
Check this PR ^^

**Pull request closed without merging**
