### PR TITLE
libpng: fix build for ppc64le

### PR DESCRIPTION
**Pull request by classilla**
The current `meson.build` for `libpng` FTBFS on VSX-capable Power ISA systems because it does not include the VSX source files or set the proper compile flags. This fixes it for little-endian, where all little-endian 64-bit Power ISA systems are reliably known to have VSX support (big-endian would require separate changes that are not currently possible with what `host_machine` reports).

### CODE REVIEW

**Comment by neheb** [comment]
releases.json needs bumping.

**Comment by classilla** [comment]
Sorry about that, bumped.

**Comment by jpakkane** [comment]
In the future please keep commits squashed to a single one.

**Comment by classilla** [comment]
Thank you, will do.

**Pull request merged**
