### PR TITLE
protobuf: update to v25.2

### PR DESCRIPTION
**Pull request by klokik**
Wanted by #1333

This now depends on `abseil-cpp` :cry:

### CODE REVIEW

**Comment by klokik** [comment]
blocked by this https://github.com/protocolbuffers/protobuf/issues/14602

**Comment by neheb** [comment]
MinGW is failing too.

**Comment by neheb** [comment]
```
 D:\a\wrapdb\wrapdb\_build/../subprojects/abseil-cpp-20230802.0/absl/synchronization/internal/per_thread_sem.cc:93:(.text+0x385): undefined reference to `absl::lts_20230802::synchronization_internal::Win32Waiter::Wait(absl::lts_20230802::synchronization_internal::KernelTimeout)'
```

abseil issue I guess.

**Comment by klokik** [comment]
Righ, my favorite chains of broken stuff

**Comment by klokik** [comment]
@neheb  how do I add `diff_files` without triggering a sanity-check warning for a `minimum meson_version '>=0.58.0' but uses features which were added in newer versions` ? Or what would you suggest?
Or it would be acceptable to bump master project requirement to meson 0.63.0 ?

**Comment by jpakkane** [comment]
> Would it be acceptable to bump master project requirement to meson>=0.63.0 ?

If it fixes your issue, sure.

**Comment by neheb** [comment]
since you're fixing exports, I wonder if gnu_symbol_visibility is applicable.

**Comment by klokik** [comment]
> I wonder if gnu_symbol_visibility is applicable.

For `protobuf(-lite)` yes, but not for `libprotoc`.

I had to default to static library, because of weird linking issues with MINGW. The rest of the platforms are fine, but I have no idea why `gcc` starts to export `absl` symbols there.

**Comment by klokik** [comment]
Checks green, but cross-compilation will not work. Fixing `protoc-native` target ...

**Comment by klokik** [comment]
Fixed cross-compilation: should be ready to go!

**Comment by jpakkane** [comment]
WrapDB does not permit code changes. We use releases as-is with only build system changes. Otherwise we have to carry the maintenance burden of keeping them up to date which is something we don't even have resources to do.

**Comment by klokik** [comment]
@jpakkane What would you suggest me to do? Should I drop MINGW from this release?

Me too isn't happy patching the source, but then, I'm afraid of falling into the rabbit-hole of fixing everything down the line. Everything is always broken somewhere and only may get fixed in the next release, that will inevitably bring other 🐞s

**Comment by klokik** [comment]
And MSVC version will be only available as a static library compiled with `/permissive`

**Comment by klokik** [comment]
Ok, that worked: downstream `abseil-cpp` is already patched, what a surprise 😏

**Comment by klokik** [comment]
Think it's ready to go?

**Pull request merged**
