### PR TITLE
libssh: add mingw support

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
ehhh ended up adding MSVC support too.

ping @ilsme

**Comment by jpakkane** [comment]
LGTM but it would be nice to get an actual usage report.

**Comment by neheb** [comment]
Should be the same. I didn't touch any include_directories.

Only real question is whether or not to have an explicit wincng option. It's Windows only anyways.

**Comment by neheb** [comment]
further examination reveals libssh2 only uses openssl's libcrypto. libssl is not used.

Wonder if dependency('openssl') should be removed in that case...

**Comment by neheb** [comment]
my CI test reveals

```
libssh2| Run-time dependency libgcrypt found: YES 1.10.1
```

is broken.

**Comment by neheb** [comment]
CI currently tests three backends: openssl, libgcrypt, and wincng. Cool.

mbedtls was tested locally to work as well.

**Comment by neheb** [comment]
ping @jpakkane

**Pull request merged**
