### PR TITLE
sdl2_image: update to 2.6.3

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by v1993** [comment]
Partially fixes #961 as is, thanks for this!

I suggest adding option `use_stbimage`. When specified, it defines `USE_STBIMAGE` macro, adds `IMG_stb.c` and drops dependencies on libpng and libjpeg for png/jpeg loaders, so those are enabled unless explicitly disabled.

`IMG_xxx.c` is a *template files to help with adding new loaders*. There's no reason to add it as source and upstream CMake indeed does not do that.

Loaders are disabled unless explicitly enabled with a define (`IMG_stb.c` is an exception due to its nature as a helper rather than loader - and even then it's `ifedef`ed beyond `USE_STBIMAGE`). This means that there's no point in adding source files unless you also enable respective `LOAD_*` macros. As a result, all unconditionally built files, sans BMP (for which `-DLOAD_BMP` is defined), do exactly nothing. IMO it would make sense to expose those as feature options as well, with `auto` value behavior mirroring defaults of upstream CMake builds.

**Comment by v1993** [comment]
Also: upstream CMake defaults avif, jxl, tiff and webp support to off. IMO it would make sense to default their values to `disabled` in this wrap as well.

Notably, upstream builds also *default* to using dependency-free STB loader for PNG/JPEG, so by default library does not depend on anything external (except SDL2, obviously).

**Comment by v1993** [comment]
Thinking about it a little more - it probably will be the best if this gets merged in current state, then I'll build upon improvements from this PR and make a separate one.

**Comment by neheb** [comment]
fair enough.

**Pull request merged**
