### PR TITLE
libebml: fix compilation with MSVC and macOS

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
```
======================================================================
ERROR: test_releases (__main__.TestReleases) (step='check_meson_version', name='openssl')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/wrapdb/wrapdb/./tools/sanity_checks.py", line 100, in check_meson_version
    subproject, = [subproj for subproj in project_info["subprojects"] if subproj["name"] == name]
ValueError: not enough values to unpack (expected 1, got 0)
```

well now. this seems unrelated.

**Comment by neheb** [comment]
Fixed.

**Comment by eli-schwartz** [comment]
Sadly there are merge conflicts.

CI passes, great. Since no effective change to meson.build occurred, can you back out the new release from releases.json? There's no need to tag anything new just to fix CI.

**Comment by neheb** [comment]
I bumped the release to get the CI to build. I remember having to do that.

**Comment by eli-schwartz** [comment]
Yeah but in this case I watched the CI pass and therefore as it is confirmed, we can now confidently merge it without the version bump ;)

**Comment by neheb** [comment]
Done.

**Pull request merged**
