### PR TITLE
gdk-pixbuf: update to 2.42.12

### PR DESCRIPTION
**Pull request by bgilbert**
Various built-in loaders are now disabled by default, so enable them in CI.

Add Python packaging module to MSYS because glib needs it.

### CODE REVIEW

**Comment by neheb** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/wrapdb/wrapdb/_build/subprojects/glib-2.80.0/gio/glib-compile-resources'
```

wonder why...

**Comment by bgilbert** [comment]
The `glib-compile-resources` error looks like a race condition that should be fixed by [this upstream PR](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/166).  The missing `packaging` package is because glib 2.80+ added a dependency on it; this also caused CI failures in #1443 but wasn't addressed there.  #1481 attempts to add support for wrap-specific Python dependencies.

**Comment by eli-schwartz** [comment]
The upstream release is also badly broken due to https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/164

**Comment by bgilbert** [comment]
Yup, was just discovering that.  The `others` option is new and wasn't added to CI.  I'll send an MR for the CI portion.

**Comment by bgilbert** [comment]
Looks like the MSYS failure is inside the glib dependency.

**Pull request merged**
