### PR TITLE
sdl2: update to 2.24.2

### PR DESCRIPTION
**Pull request by Jan200101**

### CODE REVIEW

**Comment by Jan200101** [comment]
I am happy to announce that the MacOS failure is not in my control

**Comment by neheb** [comment]
This does not build with muon. Can you take a look?

**Comment by neheb** [comment]
That's fine. The other errors are enough.

**Comment by Jan200101** [comment]
I'll see if I can fix the cmakedefine implementation in muon

**Comment by neheb** [comment]
If you're looking into fixing cmake config file handling, I'll point to https://github.com/mesonbuild/wrapdb/issues/708 as well.

Anyway, beyond the scope of this PR.

**Comment by neheb** [comment]
Tested locally. Works fine. Merging.

**Comment by Jan200101** [comment]
I've been told, and have tested, that this is not a problem with muon being more wrong but being more strict.

It follows the behavior of meson, which does not handle `#cmakedefine`s where the name and the value are not the same.

Thus my hands are tied.

**Comment by Jan200101** [comment]
https://github.com/mesonbuild/meson/issues/11006

**Pull request merged**
