### PR TITLE
ci: remove debug traces and update `build_all` python for macOS

### PR DESCRIPTION
**Pull request by benoit-pierre**
Follow up to #1630.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Is the Strawberry Perl workaround for VisualStudio not needed for `build_all` too?

**Comment by neheb** [comment]
Guess not.

**Comment by neheb** [comment]
I see EXTERNALLY-MANAGED is gone for macOS. Could this work for Alpine as well?

**Comment by benoit-pierre** [comment]
No, since chroot is used.

**Pull request merged**
