### PR TITLE
mm-common: add

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by eli-schwartz** [comment]
What do we actually need this for? It's always used as a subproject() iirc, and is only relevant when building in "maintainer mode" (a concept copied from autotools conventions into the gtkmm community's Meson ports).

**Comment by neheb** [comment]
```
 meson.build:19: WARNING: Project targets '>=0.55.0' but uses feature introduced in '0.58.0': meson.global_build_root.
```

Unrelated error.

**Comment by neheb** [comment]
Oh this is used by libxml++.

**Comment by eli-schwartz** [comment]
> Oh this is used by libxml++.

No it isn't, not unless you build libxml++ from a git checkout of libxml++.

Also they have a wrap file for this already.

**Comment by neheb** [comment]
Yeah they do. What happens with wrap_mode=forcefallback is that their mm-common.wrap file gets copied. This is wrong behavior I think.

**Comment by eli-schwartz** [comment]
> their mm-common.wrap file gets copied. This is wrong behavior I think.

If you don't think Meson should create wrap-redirect files, that can be discussed in https://github.com/mesonbuild/meson/pull/9423

I don't think it's accurate to claim that the behavior is "wrong" from a wrapdb sense, nor is the solution to add it to the wrapdb.

**Comment by neheb** [comment]
```
 AssertionError: Lists differ: ['abs[1249 chars]', 'miniz', 'minizip-ng', 'mm-common', 'mockli[1066 chars]std'] != ['abs[1249 chars]', 'mm-common', 'miniz', 'minizip-ng', 'mockli[1066 chars]std']

First differing element 109:
'miniz'
'mm-common'

Diff is 2972 characters long. Set self.maxDiff to None to see it.
```

I don't get it.

**Comment by eli-schwartz** [comment]
libxml++ works perfectly fine in CI, and it also works perfectly fine when installed into a project and built locally.

**Pull request closed without merging**
