### PR TITLE
fluidsynth: update to 2.2.6

### PR DESCRIPTION
**Pull request by kcgen**

### CODE REVIEW

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
Not relevant, but can you also fix up the broken_windows section?

**Comment by eli-schwartz** [comment]
> Not relevant, but can you also fix up the broken_windows section?

Next time please do not do this! It is line noise. Only remove the one that you are marking as no longer broken. If you want to "fix up" something that is not "broken", please submit a separate PR to reflow the list, and revert the reflowing you've already done.

This makes it easier to read the changes in this PR. Instead of looking at and trying to review a 32-line diff, you only need to look at a *one* line diff.

**Comment by kcgen** [comment]
Great point @eli-schwartz ; a good case where one-item-per line works well (alphabetic sort).  I think code reviews and diffs are the perfect scenario to encourage their use.

**Comment by neheb** [comment]
@eli-schwartz I suggest running clang-format on all the json files. Gets rid of these problems. Probably would be good to add a CI check for that too.

**Pull request merged**
