### PR TITLE
vulkan-{headers,validationlayers}: update to 1.3.229

### PR DESCRIPTION
**Pull request by Kelvium**
I've also added `[provide]` section in .wraps.

### CODE REVIEW

**Comment by neheb** [comment]
I think the actual provide should be Vulkan-Headers based on https://github.com/KhronosGroup/Vulkan-Headers/pull/207

I know @eli-schwartz isn't a big fan of adding provide to packages that don't export a pkgconfig or cmake target file.

**Comment by eli-schwartz** [comment]
The problem is that it literally doesn't work in any way shape or form for any users anywhere, because if there isn't *some* form of dependency lookup provided by the actual actual software, then people ***cannot*** use `dependency()` under any circumstances, and therefore as a result they cannot get it from a wrap fallback either.

**Comment by neheb** [comment]
Nvm the comment says

```
searched for by find_package(VulkanHeaders)
```

**Comment by jpakkane** [comment]
Since the linked issue seems to be stuck, how about dropping the provide entry from this, merging it and then adding the provide once upstream makes a decision?

**Comment by Kelvium** [comment]
> Since the linked issue seems to be stuck, how about dropping the provide entry from this, merging it and then adding the provide once upstream makes a decision?

Okay :)

**Comment by stephanlachnit** [comment]
Please do not update vulkan-validationlayers, it is essentially unusable. See https://github.com/mesonbuild/wrapdb/issues/103 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2331#issuecomment-731376649

**Pull request closed without merging**
