### PR TITLE
reflex: Update to version 5.1.0 

### PR DESCRIPTION
**Pull request by dnicolodi**

### CODE REVIEW

**Comment by dnicolodi** [comment]
It seems that I'm hitting a compiler bug trying to use this:
```
[1/13] Compiling C++ object subprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p/lib_simd_avx512bw.cpp.o
FAILED: subprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p/lib_simd_avx512bw.cpp.o
ccache c++ -Isubprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p -Isubprojects/RE-flex-5.1.0 -I../../subprojects/RE-flex-5.1.0 -I../../subprojects/RE-flex-5.1.0/include -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -O3 -Wno-non-virtual-dtor -DHAVE_AVX512BW -mavx512bw -MD -MQ subprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p/lib_simd_avx512bw.cpp.o -MF subprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p/lib_simd_avx512bw.cpp.o.d -o subprojects/RE-flex-5.1.0/liblibsimd_avx512bw.a.p/lib_simd_avx512bw.cpp.o -c ../../subprojects/RE-flex-5.1.0/lib/simd_avx512bw.cpp
fatal error: error in backend: Cannot select: 0x7fe90505a2d0: v8i64 = X86ISD::PCMPEQ 0x7fe905072638, 0x7fe90505a540
  0x7fe905072638: v8i64,ch = load<(load (s64) from %ir.36, align 1, !tbaa !10), zext from v8i8> 0x7fe90390e368, 0x7fe905071868, undef:i64
    0x7fe905071868: i64 = add 0x7fe905072158, Constant:i64<8>
      0x7fe905072158: i64 = add 0x7fe90505a610, 0x7fe905071c10
        0x7fe90505a610: i64,ch = CopyFromReg 0x7fe90390e368, Register:i64 %0
          0x7fe90505a5a8: i64 = Register %0
        0x7fe905071c10: i64,ch = CopyFromReg 0x7fe90390e368, Register:i64 %10
          0x7fe90505a678: i64 = Register %10
      0x7fe905072430: i64 = Constant<8>
    0x7fe905071f50: i64 = undef
  0x7fe90505a540: v8i64,ch = X86ISD::VBROADCAST_LOAD<(load (s64) from constant-pool)> 0x7fe90390e368, 0x7fe90505a818
    0x7fe90505a818: i64 = X86ISD::WrapperRIP TargetConstantPool:i64<i64 10> 0
      0x7fe905071938: i64 = TargetConstantPool<i64 10> 0
In function: _ZN6reflex21simd_nlcount_avx512bwERPKcS1_
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```
but only if I compile it as subproject in a specific project. If I compile the subproject as part of the wrapdb project all works fine. As far as I can tell the build options are exactly the same between the two builds. Has anyone ever seen something like this?

**Comment by neheb** [comment]
That looks like an LLVM bug.

**Comment by dnicolodi** [comment]
That is what I think it is. The difference is that I compile with `-O3` in my project and wrapdb uses `-O0`. It goes away when compiling with `-O0`. Should I add the work-around to the wrap?

**Comment by dnicolodi** [comment]
I hit the bug with clang 14.0 on macOS. It would be nice if someone could check if it is platform specific...

**Comment by neheb** [comment]
env CXX=clang++ meson -Dwraps=reflex -Dbuildtype=release a

compiles on Linux.

**Comment by dnicolodi** [comment]
With which version of clang?

**Comment by neheb** [comment]
18.1.8

**Pull request merged**
