### PR TITLE
liblzma: allow threads to be disabled

### PR DESCRIPTION
**Pull request by Gottox**
This is useful for systems that change their behavior based on the presence of threads, notably emscripten.

### CODE REVIEW

**Comment by jpakkane** [comment]
You need to add a new entry to `releases.json`, specifically `5.2.11-2`.

**Comment by Gottox** [comment]
fixed.

**Comment by eli-schwartz** [comment]
create_release failed with: "Failed to resolve action download info. Error: Internal Server Error"

Was wondering why no automatically triggered release...

**Comment by neheb** [comment]
@Gottox you think an emscripten CI should be added?

**Comment by Gottox** [comment]
Well, why not? 😄

**Pull request merged**
