### PR TITLE
Add Cairo.

### PR DESCRIPTION
**Pull request by jpakkane**

### CODE REVIEW

**Comment by xclaesse** [comment]
Dunno why all tests fails so bad, but could just disable them I guess.

**Comment by jpakkane** [comment]
It's a timeout, so maybe it needs `buildtype=debugoptimized`? That does not help with VS's configuration warning, though.

**Comment by xclaesse** [comment]
CI often need --time-multiplier because they could run on slower machines.

**Comment by eli-schwartz** [comment]
There is one timeout, but also one outright failure. Not sure what is up with that.

**Comment by xclaesse** [comment]
Checked how upstream run their CI and they have `--no-suite=slow`.

**Comment by xclaesse** [comment]
Running tests requires specific hacks: https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/.gitlab-ci.yml#L202. Even `-Dcair:tests=disabled` is not enough, which is an upstream issue.

Since we are not upstream's CI and there is nothing we can do on our side since the Meson build definition comes from upstream, there is no point in running tests here. Added an option to skip that completely.

**Comment by neheb** [comment]
```
2022-09-02T14:46:38.9970805Z Running custom install script 'C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\python.exe D:\\a\\wrapdb\\wrapdb\\subprojects\\fontconfig\\conf.d\\link_confs.py c:/share/fontconfig/conf.avail c:/etc/fonts/conf.d 10-hinting-slight.conf 10-scale-bitmap-fonts.conf 11-lcdfilter-default.conf 20-unhint-small-vera.conf 30-metric-aliases.conf 40-nonlatin.conf 45-generic.conf 45-latin.conf 48-spacing.conf 49-sansserif.conf 50-user.conf 51-local.conf 60-generic.conf 60-latin.conf 65-fonts-persian.conf 65-nonlatin.conf 69-unifont.conf 80-delicious.conf 90-synthetic.conf'
2022-09-02T14:46:38.9971809Z --- stdout ---
2022-09-02T14:46:38.9971933Z 
2022-09-02T14:46:38.9972044Z --- stderr ---
2022-09-02T14:46:38.9972265Z Traceback (most recent call last):
2022-09-02T14:46:38.9972403Z 
2022-09-02T14:46:38.9972617Z   File "D:\a\wrapdb\wrapdb\subprojects\fontconfig\conf.d\link_confs.py", line 25, in <module>
2022-09-02T14:46:38.9972858Z 
2022-09-02T14:46:38.9972951Z     os.makedirs(confpath)
2022-09-02T14:46:38.9973093Z 
2022-09-02T14:46:38.9973348Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\os.py", line 215, in makedirs
2022-09-02T14:46:38.9973574Z 
2022-09-02T14:46:38.9973678Z     makedirs(head, exist_ok=exist_ok)
2022-09-02T14:46:38.9973815Z 
2022-09-02T14:46:38.9974007Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\os.py", line 215, in makedirs
2022-09-02T14:46:38.9974220Z 
2022-09-02T14:46:38.9974324Z     makedirs(head, exist_ok=exist_ok)
2022-09-02T14:46:38.9974471Z 
2022-09-02T14:46:38.9974649Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\os.py", line 215, in makedirs
2022-09-02T14:46:38.9974868Z 
2022-09-02T14:46:38.9974959Z     makedirs(head, exist_ok=exist_ok)
2022-09-02T14:46:38.9975106Z 
2022-09-02T14:46:38.9975292Z   File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\os.py", line 225, in makedirs
2022-09-02T14:46:38.9975506Z 
2022-09-02T14:46:38.9975589Z     mkdir(name, mode)
2022-09-02T14:46:38.9975714Z 
2022-09-02T14:46:38.9976079Z OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\a\\wrapdb\\wrapdb\\_build\\pkg\\:'
2022-09-02T14:46:38.9976343Z 
2022-09-02T14:46:38.9976348Z 
2022-09-02T14:46:38.9977588Z FAILED: install script 'C:\hostedtoolcache\windows\Python\3.9.13\x64\python.exe D:\a\wrapdb\wrapdb\subprojects\fontconfig\conf.d\link_confs.py c:/share/fontconfig/conf.avail c:/etc/fonts/conf.d 10-hinting-slight.conf 10-scale-bitmap-fonts.conf 11-lcdfilter-default.conf 20-unhint-small-vera.conf 30-metric-aliases.conf 40-nonlatin.conf 45-generic.conf 45-latin.conf 48-spacing.conf 49-sansserif.conf 50-user.conf 51-local.conf 60-generic.conf 60-latin.conf 65-fonts-persian.conf 65-nonlatin.conf 69-unifont.conf 80-delicious.conf 90-synthetic.conf' exit code 1, stopped
2022-09-02T14:46:39.3974336Z .
```

windows = false?

**Comment by xclaesse** [comment]
It is supposed to work on Windows, GStreamer uses it intensively. The problem seems to be in a fontconfig script, maybe we need more recent fontconfig wrap or something.

**Comment by eli-schwartz** [comment]
The additions to the sanity check framework*must* be in their own commit.

In general I think this can be quite useful, specifically the option to control the test command, but the use case I had in mind was running a custom test command with `xvfb-run` *before* `meson test`. I wonder if we could somehow make that work?

**Comment by xclaesse** [comment]
> The additions to the sanity check framework _must_ be in their own commit.

done



> In general I think this can be quite useful, specifically the option to control the test command, but the use case I had in mind was running a custom test command with `xvfb-run` _before_ `meson test`. I wonder if we could somehow make that work?

Isn't that what `--wrapper` does?

> The problem seems to be in a fontconfig script, maybe we need more recent fontconfig wrap or something.

Added fontconfig to this PR because cairo upstream has a fontconfig.wrap that uses git main branch that currently fails to install on Windows: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/326. This PR will now overrides that wrap with latest release instead.

**Comment by xclaesse** [comment]
The good new is it now pass on Windows. The bad news is it now fails on Linux. Made a fix for upstream: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/merge_requests/230.

**Comment by xclaesse** [comment]
> Made a fix for upstream: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/merge_requests/230.

That MR should also fix the regression when installing into a DESTDIR on Windows. Hopefully next release of cairo will pass WrapDB CI.

**Pull request closed without merging**
