### PR TITLE
glib: update to 2.80.5

### PR DESCRIPTION
**Pull request by benoit-pierre**
https://gitlab.gnome.org/GNOME/glib/-/releases/2.80.5

### CODE REVIEW

**Comment by benoit-pierre** [comment]
About the usual failures: it looks like we're hitting a variant of https://github.com/actions/runner-images/issues/7218. Patching the glib build can work around that:
```diff
--- a/tests/meson.build	
+++ b/tests/meson.build
@@ -15,7 +15,8 @@
 if have_bash
   foreach test_name : lint_scripts
     test(
-      test_name, files(test_name),
+      test_name, bash,
+      args : [files(test_name)],
       env : test_env,
       suite : ['lint', 'no-valgrind'],
       protocol : 'tap',
```

**Comment by bgilbert** [comment]
Ah, yup, it's an upstream bug.  Thanks for tracking that down!  Upstream PR [here](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4219), validated [here](https://github.com/bgilbert/wrapdb/actions/runs/10583840916).

Meanwhile, these are just the usual test failures, so let's merge this.

**Comment by bgilbert** [comment]
Fix landed upstream and will be in 2.82.1.

**Comment by bgilbert** [comment]
@neheb, is this blocked on anything?

**Pull request merged**
