### PR TITLE
add oatpp-zlib module

### PR DESCRIPTION
**Pull request by Totto16**
Add oatpp-zlib
The repo can be found [here](https://github.com/oatpp/oatpp-zlib)

### CODE REVIEW

**Comment by neheb** [comment]
rebase maybe?

**Comment by Totto16** [comment]
Like I thought and looked up on the official Documentation, 32 Bit is not supported, it happens to work with all other `oatpp-*` modules I ported so far, but for this one it does not, it is complicated to setup a test environment for me, so I think it would be okay, to not support 32 bit here...

But how can that be done? Any suggestions?
Just fail in the meson.build if the e.g. ```build_machine.cpu_family() == 'x86'`` ?`

**Comment by neheb** [comment]
So clang32 is the only 32 bit CI. Might fail on Linux 32-bit too.

**Comment by Totto16** [comment]
❤️

**Pull request merged**
