### PR TITLE
absl-cpp: more `provides` aliases

### PR DESCRIPTION
**Pull request by klokik**
This adds more aliases to dependencies created by `absl-cpp` meson.build file.

For self-contained build of #1234

### CODE REVIEW

**Comment by klokik** [comment]
May add more aliases later on for other gRPC needs

**Comment by klokik** [comment]
hm, should update absl-cpp version suffix

**Comment by klokik** [comment]
Can I do something more to get this merged?

It shouldn't have conflicts with the update of abseil at #1180

**Comment by neheb** [comment]
how does this work if meson.build is not modified to add the extra dependencies?

**Comment by klokik** [comment]
It reuses existing dependencies within meson.build.

Abseil libs in pkg-config distribution variant are very granular for whatever reason, but existing wrapdb version of it creates just a few larger libraries/dependencies that provide same symbols. I guess it is done that way for easier maintenance.

So if one wants `absl_flat_hash_map` or `absl_flat_hash_set`, it will be given whole `absl_containers_dep`. Same with other dependencies. Most header-only absl libraries will get `absl_base_dep` (even though it is not entirely correct) because it provides necessary include paths.

**Comment by klokik** [comment]
Maintaining that manually should be tiresome.
```
$ ls -1 /usr/lib/pkgconfig/absl_*
/usr/lib/pkgconfig/absl_absl_check.pc
/usr/lib/pkgconfig/absl_absl_log.pc
/usr/lib/pkgconfig/absl_algorithm.pc
/usr/lib/pkgconfig/absl_algorithm_container.pc
/usr/lib/pkgconfig/absl_any.pc
/usr/lib/pkgconfig/absl_any_invocable.pc
/usr/lib/pkgconfig/absl_atomic_hook.pc
/usr/lib/pkgconfig/absl_bad_any_cast.pc
/usr/lib/pkgconfig/absl_bad_any_cast_impl.pc
/usr/lib/pkgconfig/absl_bad_optional_access.pc
/usr/lib/pkgconfig/absl_bad_variant_access.pc
/usr/lib/pkgconfig/absl_base.pc
/usr/lib/pkgconfig/absl_base_internal.pc
/usr/lib/pkgconfig/absl_bind_front.pc
/usr/lib/pkgconfig/absl_bits.pc
/usr/lib/pkgconfig/absl_btree.pc
/usr/lib/pkgconfig/absl_check.pc
/usr/lib/pkgconfig/absl_city.pc
/usr/lib/pkgconfig/absl_civil_time.pc
/usr/lib/pkgconfig/absl_cleanup.pc
/usr/lib/pkgconfig/absl_cleanup_internal.pc
/usr/lib/pkgconfig/absl_common_policy_traits.pc
/usr/lib/pkgconfig/absl_compare.pc
/usr/lib/pkgconfig/absl_compressed_tuple.pc
/usr/lib/pkgconfig/absl_config.pc
/usr/lib/pkgconfig/absl_container_common.pc
/usr/lib/pkgconfig/absl_container_memory.pc
/usr/lib/pkgconfig/absl_cord.pc
/usr/lib/pkgconfig/absl_cord_internal.pc
/usr/lib/pkgconfig/absl_cord_test_helpers.pc
/usr/lib/pkgconfig/absl_cordz_functions.pc
/usr/lib/pkgconfig/absl_cordz_handle.pc
/usr/lib/pkgconfig/absl_cordz_info.pc
/usr/lib/pkgconfig/absl_cordz_sample_token.pc
/usr/lib/pkgconfig/absl_cordz_statistics.pc
/usr/lib/pkgconfig/absl_cordz_update_scope.pc
/usr/lib/pkgconfig/absl_cordz_update_tracker.pc
/usr/lib/pkgconfig/absl_core_headers.pc
/usr/lib/pkgconfig/absl_counting_allocator.pc
/usr/lib/pkgconfig/absl_crc32c.pc
/usr/lib/pkgconfig/absl_crc_cord_state.pc
/usr/lib/pkgconfig/absl_crc_cpu_detect.pc
/usr/lib/pkgconfig/absl_crc_internal.pc
/usr/lib/pkgconfig/absl_debugging.pc
/usr/lib/pkgconfig/absl_debugging_internal.pc
/usr/lib/pkgconfig/absl_demangle_internal.pc
/usr/lib/pkgconfig/absl_die_if_null.pc
/usr/lib/pkgconfig/absl_dynamic_annotations.pc
/usr/lib/pkgconfig/absl_endian.pc
/usr/lib/pkgconfig/absl_errno_saver.pc
/usr/lib/pkgconfig/absl_examine_stack.pc
/usr/lib/pkgconfig/absl_exponential_biased.pc
/usr/lib/pkgconfig/absl_failure_signal_handler.pc
/usr/lib/pkgconfig/absl_fast_type_id.pc
/usr/lib/pkgconfig/absl_fixed_array.pc
/usr/lib/pkgconfig/absl_flags.pc
/usr/lib/pkgconfig/absl_flags_commandlineflag.pc
/usr/lib/pkgconfig/absl_flags_commandlineflag_internal.pc
/usr/lib/pkgconfig/absl_flags_config.pc
/usr/lib/pkgconfig/absl_flags_internal.pc
/usr/lib/pkgconfig/absl_flags_marshalling.pc
/usr/lib/pkgconfig/absl_flags_parse.pc
/usr/lib/pkgconfig/absl_flags_path_util.pc
/usr/lib/pkgconfig/absl_flags_private_handle_accessor.pc
/usr/lib/pkgconfig/absl_flags_program_name.pc
/usr/lib/pkgconfig/absl_flags_reflection.pc
/usr/lib/pkgconfig/absl_flags_usage.pc
/usr/lib/pkgconfig/absl_flags_usage_internal.pc
/usr/lib/pkgconfig/absl_flat_hash_map.pc
/usr/lib/pkgconfig/absl_flat_hash_set.pc
/usr/lib/pkgconfig/absl_function_ref.pc
/usr/lib/pkgconfig/absl_graphcycles_internal.pc
/usr/lib/pkgconfig/absl_hash.pc
/usr/lib/pkgconfig/absl_hash_function_defaults.pc
/usr/lib/pkgconfig/absl_hash_policy_traits.pc
/usr/lib/pkgconfig/absl_hash_testing.pc
/usr/lib/pkgconfig/absl_hashtable_debug.pc
/usr/lib/pkgconfig/absl_hashtable_debug_hooks.pc
/usr/lib/pkgconfig/absl_hashtablez_sampler.pc
/usr/lib/pkgconfig/absl_if_constexpr.pc
/usr/lib/pkgconfig/absl_inlined_vector.pc
/usr/lib/pkgconfig/absl_inlined_vector_internal.pc
/usr/lib/pkgconfig/absl_int128.pc
/usr/lib/pkgconfig/absl_kernel_timeout_internal.pc
/usr/lib/pkgconfig/absl_layout.pc
/usr/lib/pkgconfig/absl_leak_check.pc
/usr/lib/pkgconfig/absl_log.pc
/usr/lib/pkgconfig/absl_log_entry.pc
/usr/lib/pkgconfig/absl_log_flags.pc
/usr/lib/pkgconfig/absl_log_globals.pc
/usr/lib/pkgconfig/absl_log_initialize.pc
/usr/lib/pkgconfig/absl_log_internal_append_truncated.pc
/usr/lib/pkgconfig/absl_log_internal_check_impl.pc
/usr/lib/pkgconfig/absl_log_internal_check_op.pc
/usr/lib/pkgconfig/absl_log_internal_conditions.pc
/usr/lib/pkgconfig/absl_log_internal_config.pc
/usr/lib/pkgconfig/absl_log_internal_flags.pc
/usr/lib/pkgconfig/absl_log_internal_format.pc
/usr/lib/pkgconfig/absl_log_internal_globals.pc
/usr/lib/pkgconfig/absl_log_internal_log_impl.pc
/usr/lib/pkgconfig/absl_log_internal_log_sink_set.pc
/usr/lib/pkgconfig/absl_log_internal_message.pc
/usr/lib/pkgconfig/absl_log_internal_nullguard.pc
/usr/lib/pkgconfig/absl_log_internal_nullstream.pc
/usr/lib/pkgconfig/absl_log_internal_proto.pc
/usr/lib/pkgconfig/absl_log_internal_strip.pc
/usr/lib/pkgconfig/absl_log_internal_structured.pc
/usr/lib/pkgconfig/absl_log_internal_voidify.pc
/usr/lib/pkgconfig/absl_log_severity.pc
/usr/lib/pkgconfig/absl_log_sink.pc
/usr/lib/pkgconfig/absl_log_sink_registry.pc
/usr/lib/pkgconfig/absl_log_streamer.pc
/usr/lib/pkgconfig/absl_log_structured.pc
/usr/lib/pkgconfig/absl_low_level_hash.pc
/usr/lib/pkgconfig/absl_malloc_internal.pc
/usr/lib/pkgconfig/absl_memory.pc
/usr/lib/pkgconfig/absl_meta.pc
/usr/lib/pkgconfig/absl_node_hash_map.pc
/usr/lib/pkgconfig/absl_node_hash_set.pc
/usr/lib/pkgconfig/absl_node_slot_policy.pc
/usr/lib/pkgconfig/absl_non_temporal_arm_intrinsics.pc
/usr/lib/pkgconfig/absl_non_temporal_memcpy.pc
/usr/lib/pkgconfig/absl_nullability.pc
/usr/lib/pkgconfig/absl_numeric.pc
/usr/lib/pkgconfig/absl_numeric_representation.pc
/usr/lib/pkgconfig/absl_optional.pc
/usr/lib/pkgconfig/absl_periodic_sampler.pc
/usr/lib/pkgconfig/absl_prefetch.pc
/usr/lib/pkgconfig/absl_pretty_function.pc
/usr/lib/pkgconfig/absl_random_bit_gen_ref.pc
/usr/lib/pkgconfig/absl_random_distributions.pc
/usr/lib/pkgconfig/absl_random_internal_distribution_caller.pc
/usr/lib/pkgconfig/absl_random_internal_distribution_test_util.pc
/usr/lib/pkgconfig/absl_random_internal_fast_uniform_bits.pc
/usr/lib/pkgconfig/absl_random_internal_fastmath.pc
/usr/lib/pkgconfig/absl_random_internal_generate_real.pc
/usr/lib/pkgconfig/absl_random_internal_iostream_state_saver.pc
/usr/lib/pkgconfig/absl_random_internal_mock_helpers.pc
/usr/lib/pkgconfig/absl_random_internal_nonsecure_base.pc
/usr/lib/pkgconfig/absl_random_internal_pcg_engine.pc
/usr/lib/pkgconfig/absl_random_internal_platform.pc
/usr/lib/pkgconfig/absl_random_internal_pool_urbg.pc
/usr/lib/pkgconfig/absl_random_internal_randen.pc
/usr/lib/pkgconfig/absl_random_internal_randen_engine.pc
/usr/lib/pkgconfig/absl_random_internal_randen_hwaes.pc
/usr/lib/pkgconfig/absl_random_internal_randen_hwaes_impl.pc
/usr/lib/pkgconfig/absl_random_internal_randen_slow.pc
/usr/lib/pkgconfig/absl_random_internal_salted_seed_seq.pc
/usr/lib/pkgconfig/absl_random_internal_seed_material.pc
/usr/lib/pkgconfig/absl_random_internal_traits.pc
/usr/lib/pkgconfig/absl_random_internal_uniform_helper.pc
/usr/lib/pkgconfig/absl_random_internal_wide_multiply.pc
/usr/lib/pkgconfig/absl_random_mocking_bit_gen.pc
/usr/lib/pkgconfig/absl_random_random.pc
/usr/lib/pkgconfig/absl_random_seed_gen_exception.pc
/usr/lib/pkgconfig/absl_random_seed_sequences.pc
/usr/lib/pkgconfig/absl_raw_hash_map.pc
/usr/lib/pkgconfig/absl_raw_hash_set.pc
/usr/lib/pkgconfig/absl_raw_logging_internal.pc
/usr/lib/pkgconfig/absl_sample_recorder.pc
/usr/lib/pkgconfig/absl_scoped_mock_log.pc
/usr/lib/pkgconfig/absl_scoped_set_env.pc
/usr/lib/pkgconfig/absl_span.pc
/usr/lib/pkgconfig/absl_spinlock_wait.pc
/usr/lib/pkgconfig/absl_spy_hash_state.pc
/usr/lib/pkgconfig/absl_stacktrace.pc
/usr/lib/pkgconfig/absl_status.pc
/usr/lib/pkgconfig/absl_statusor.pc
/usr/lib/pkgconfig/absl_str_format.pc
/usr/lib/pkgconfig/absl_str_format_internal.pc
/usr/lib/pkgconfig/absl_strerror.pc
/usr/lib/pkgconfig/absl_string_view.pc
/usr/lib/pkgconfig/absl_strings.pc
/usr/lib/pkgconfig/absl_strings_internal.pc
/usr/lib/pkgconfig/absl_symbolize.pc
/usr/lib/pkgconfig/absl_synchronization.pc
/usr/lib/pkgconfig/absl_throw_delegate.pc
/usr/lib/pkgconfig/absl_time.pc
/usr/lib/pkgconfig/absl_time_zone.pc
/usr/lib/pkgconfig/absl_type_traits.pc
/usr/lib/pkgconfig/absl_utility.pc
/usr/lib/pkgconfig/absl_variant.pc
```

**Pull request merged**
