### PR TITLE
protobuf: provide protoc program

### PR DESCRIPTION
**Pull request by dvrogozh**
Fixes: #1052

### CODE REVIEW

**Comment by neheb** [comment]
Need to bump releases.json

**Comment by dvrogozh** [comment]
> Need to bump releases.json

Added "3.21.12-3" to versions. I hope I guessed right what needs to be done from other commits to releases.json.

**Comment by neheb** [comment]
Ah yes program_names is also needed. See the rest of the file for a hint.

**Comment by dvrogozh** [comment]
> Ah yes program_names is also needed. See the rest of the file for a hint.

Added.

**Pull request merged**
