### PR TITLE
Silence warnings on msvc

### PR DESCRIPTION
**Pull request by barcharcraz**
msvc emits more warnings than gcc at equivalent meson warning_levels, silence the ones coming from zlib.

(maybe we should just set the warning level to zero in the wrap instead ...)

### CODE REVIEW

**Comment by jpakkane** [comment]
You need to add a new release to the release json file.

**Comment by barcharcraz** [comment]
Alright I updated that file, and it looks like the rest of the instructions for contributions don't apply to simple updates.

**Comment by eli-schwartz** [comment]
Really, the changes should be squashed into one commit...

Other than that it seems fine.

**Comment by jpakkane** [comment]
I'll merge this with Github's squash thingy.

**Pull request merged**
