### PR TITLE
libffi: Update to latest upstream PR version

### PR DESCRIPTION
**Pull request by xclaesse**
This uses meson port from https://github.com/libffi/libffi/pull/746 as of 2023-08-16.

### CODE REVIEW

**Comment by neheb** [comment]
Rebase against master.

**Comment by xclaesse** [comment]
> Rebase against master.

Done, but some mingw tests fails and that's something I saw on upstream PR as well. That could be a real issue that needs investigation.

**Comment by benoit-pierre** [comment]
I suggest skipping the hung test on VisualStudio, and mark the expected failures on MSYS2:

```diff
 .../packagefiles/libffi/testsuite/meson.build      | 34 +++++++++++++++++++++-
 1 file changed, 33 insertions(+), 1 deletion(-)

diff --git c/subprojects/packagefiles/libffi/testsuite/meson.build w/subprojects/packagefiles/libffi/testsuite/meson.build
index 7aec821..976528c 100644
--- c/subprojects/packagefiles/libffi/testsuite/meson.build
+++ w/subprojects/packagefiles/libffi/testsuite/meson.build
@@ -255,6 +255,34 @@ if cc.get_id() == 'gcc'
   endif
 endif
 
+xfails = {}
+if target == 'X86_WIN32' and cc.get_id() == 'clang'
+  xfails += {
+    'bhaible / test-callback -O0 -DDGTEST=54': true,
+    'bhaible / test-callback -O0 -DDGTEST=55': true,
+    'bhaible / test-callback -O0 -DDGTEST=56': true,
+    'bhaible / test-callback -O2 -DDGTEST=54': true,
+    'bhaible / test-callback -O2 -DDGTEST=55': true,
+    'bhaible / test-callback -O2 -DDGTEST=56': true,
+    'bhaible / test-call -O0 -DDGTEST=55': true,
+    'bhaible / test-call -O0 -DDGTEST=56': true,
+    'bhaible / test-call -O0 -DDGTEST=57': true,
+    'bhaible / test-call -O2 -DDGTEST=55': true,
+    'bhaible / test-call -O2 -DDGTEST=56': true,
+    'bhaible / test-call -O2 -DDGTEST=57': true,
+    'call / s55 -O0': true,
+    'call / s55 -O2': true,
+  }
+endif
+
+skips = {}
+if target == 'X86_WIN64' and cc.get_id() == 'clang-cl'
+  skips += {
+    # Hangs indefinitely…
+    'closures / unwindtest_ffi_call': true,
+  }
+endif
+
 foreach suite, sources : tests
   # Skip this set of tests if the feature is not supported
   if suite in feature_check
@@ -336,6 +364,10 @@ foreach suite, sources : tests
             test_name += ' ' + ' '.join(matrix_c_args)
             exe_name += ''.join(matrix_c_args).underscorify()
           endif
+          test_id = ' / '.join(suite, test_name)
+          if skips.get(test_id, false)
+            continue
+          endif
           exe = executable(exe_name, src,
             dependencies: ffi_dep,
             c_args: [common_c_args, suite_c_args, matrix_c_args],
@@ -343,7 +375,7 @@ foreach suite, sources : tests
             # Not supported by Meson < 0.64, but -Ox in c_args takes precedence
             #override_options: ['optimization=plain'],
           )
-          test(test_name, exe, suite: suite)
+          test(test_name, exe, suite: suite, should_fail: xfails.get(test_id, false))
         endforeach
       endforeach
     endforeach
```

**Comment by xclaesse** [comment]
Interestingly, it timeout with MSVC x86 (not only clang): https://github.com/libffi/libffi/actions/runs/6042444795/job/16397566776?pr=746.

**Comment by xclaesse** [comment]
Let's merge this because it's fixing some issues and the version we have in wrapdb currently is not passing CI neither.

**Pull request merged**
