### PR TITLE
SDL2: fixes

### PR DESCRIPTION
**Pull request by Jan200101**
- define a test library to be used when compiling the tests (talked about in #574)
- Fix dependencies not outwardly being defined (reported in #521)

### CODE REVIEW

**Comment by neheb** [comment]
So libglvnd as in that PR does not provide a gl deep but an opengl one. Would it make sense to fall back to opengl?

**Comment by Jan200101** [comment]
> So libglvnd as in that PR does not provide a gl dep but an opengl one. Would it make sense to fall back to opengl?

there is technically a difference between libgl and libopengl, but SDL does not care about the details, so its best to rewrite it to accept both

**Comment by neheb** [comment]
Another thing. I see in ci_config.json there's pkg-config and wayland-protocols. The former seems redundant and the latter has a wrap.

**Comment by eli-schwartz** [comment]
While you're at it, I discovered that this wrap doesn't compile on my machine if I have libunwind installed -- it probes for headers and doesn't link to the pkg-config dependency or even a find_library().

**Comment by Jan200101** [comment]
the libunwind problem has been fixed in the same way upstream does it.

Lets defer merging this for a bit so that more eyes can look at this and give feedback and so I can find a MacOS machine for #455

**Comment by Jan200101** [comment]
rebased onto master to get the CI PR in
enabled basic BSD support
hopefully fix the MacOS CI? I have no idea why the build_all workflow wasn't working since the PR checks always worked fine and I couldn't reproduce this in a VM so fingers crossed?

If anything else needs doing throw it

**Comment by neheb** [comment]
@xclaesse what do you think?

**Comment by Jan200101** [comment]
> enabled basic BSD support
Turns out, FreeBSD cannot compile the tests correctly
so I need to figure that out

**Comment by eli-schwartz** [comment]
The CI for this never ran, because it didn't update the sdl2 version. Is this actually known to work? Was it intentionally merged as a source-only update without releasing a new version?

**Comment by Jan200101** [comment]
> The CI for this never ran, because it didn't update the sdl2 version.

If this is in regards to the "fix Darwin CI" commit, this was to reference #455.
CI in previous PRs always worked on MacOS and only the build_all solution failed.
I couldn't reproduce this in a MacOS VM but for some reason the Runner corrupt packages preinstalled or had some kind of configuration that wasn't reproducable on my end

> Is this actually known to work?
- Linux yes
- Windows No idea
- (Free)BSD No
- MacOS No idea

**Comment by eli-schwartz** [comment]
It's actually in regard to "I thought this was still a work in progress PR and was surprised to see it merged".

**Pull request merged**
