### PR TITLE
entt: prefer `src` directory over `single_include`

### PR DESCRIPTION
**Pull request by crispyricepc**
Using `#include <entt/entt.hpp>` is still possible with this change, but now people who prefer the forward declarations in `fwd.hpp` can also use it

### CODE REVIEW

**Comment by neheb** [comment]
need to bump releases.json

**Comment by neheb** [comment]
eh no you have to make a separate entry.

**Comment by eli-schwartz** [comment]
The changes should be squashed together, BTW.

**Comment by crispyricepc** [comment]
Okay sorry, first PR over here. Think I fixed it?

**Comment by neheb** [comment]
reverse the order in releases.json

**Comment by crispyricepc** [comment]
Ah ff-
Thanks for your patience

**Review by eli-schwartz — APPROVED** [review]
LGTM once CI passes

**Pull request merged**
