### PR TITLE
Fix required Meson version for cjson

### PR DESCRIPTION
**Pull request by tristan957**

### CODE REVIEW

**Comment by tristan957** [comment]
Found in Meson 0.64.0

**Comment by eli-schwartz** [comment]
Haven't actually checked... What's the FeatureNew that gets triggered?

**Comment by tristan957** [comment]
https://github.com/hse-project/ci-images/actions/runs/3464438836/jobs/5785961234#step:14:89

**Comment by eli-schwartz** [comment]
Makes sense, can you add a teeny tiny note to the commit message? :)

**Pull request merged**
