### PR TITLE
libusb: honor 'examples' and 'tests' options

### PR DESCRIPTION
**Pull request by Spadi0**
The Meson build options `examples` and `tests` did previously exist, but were not honored.

### CODE REVIEW

**Comment by neheb** [comment]
I'd prefer using subdir_done() instead.

**Comment by Spadi0** [comment]
@neheb I've changed the code to use `subdir_done()` instead. :+1:

**Comment by Spadi0** [comment]
:thinking: So the CI fails, but the problem is not in a part of the code I've touched. I can bump the minimum Meson version as another commit in this PR, which should fix this problem - do you want me to do that?

**Comment by neheb** [comment]
I'd rather fix the problem directly than increase the version. Although it probably doesn't build with meson that old anyway...

**Comment by Spadi0** [comment]
Ok, I authored a new commit which fixes the build without bumping the minimum required Meson version. It seems to build fine on my machine - hopefully the CI concurs... :crossed_fingers:

**Pull request merged**
