### PR TITLE
libevdev: add 1.13.1

### PR DESCRIPTION
**Pull request by benoit-pierre**
Upstream: https://gitlab.freedesktop.org/libevdev/libevdev.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
So how do you handle Linux only packages that support meson, but don't show an `unsuported …` error on other OSs?

**Comment by neheb** [comment]
Fix upstream I guess

**Comment by benoit-pierre** [comment]
Seeing as `tools/sanity_checks.py` would be happy with a failed required dependency check, then I don't see why a failed `cc.find_library(…)` or `cc.has_header(…)` check is not similarly accepted.

**Comment by neheb** [comment]
So one way to fix this is to copy the meson.build file to packagefiles and fix it up such that it passes CI.

**Comment by benoit-pierre** [comment]
Can this be merged as-is? On Linux is supported by upstream, I see no point in messing around with the original meson.build.

**Comment by jpakkane** [comment]
Failing tests are not permitted, you need to edit the wrapdb metadata files so that the build is skipped on Windows.

**Pull request closed without merging**
