### PR TITLE
libwebp: add version 1.3.1

### PR DESCRIPTION
**Pull request by benoit-pierre**
Support building all the libraries, including `libwebpdecoder`.

Not all the executables are built (only the bare minimum to check the dependencies are correctly specified).

No tests, as the only ones provided are for fuzzing and need to be build with clang.

### CODE REVIEW

**Comment by xclaesse** [comment]
Any chance this could be upstreamed?

**Comment by benoit-pierre** [comment]
> Any chance this could be upstreamed?

No idea.

**Comment by benoit-pierre** [comment]
I don't know why the MSYS2-UCRT64 build failed… I just squashed the fixups, it's the exact same code as dec90b5. ¯\\_(ツ)_/¯

**Comment by neheb** [comment]
> I don't know why the MSYS2-UCRT64 build failed… I just squashed the fixups, it's the exact same code as [dec90b5](https://github.com/mesonbuild/wrapdb/commit/dec90b53d989622bf408e770fc67e136bd38813f). ¯\_(ツ)_/¯

well known transient error with python under MSYS2. Fixed by python 3.11. Requires adding update: true in the yml files.

**Comment by benoit-pierre** [comment]
> > I don't know why the MSYS2-UCRT64 build failed… I just squashed the fixups, it's the exact same code as [dec90b5](https://github.com/mesonbuild/wrapdb/commit/dec90b53d989622bf408e770fc67e136bd38813f). ¯_(ツ)_/¯
> 
> well known transient error with python under MSYS2. Fixed by python 3.11. Requires adding update: true in the yml files.

Can you elaborate?

**Comment by neheb** [comment]
https://github.com/mesonbuild/meson/commit/3752041c8d56c7667bc0fe644fda6c2834d6aaf8

**Comment by benoit-pierre** [comment]
> [mesonbuild/meson@3752041](https://github.com/mesonbuild/meson/commit/3752041c8d56c7667bc0fe644fda6c2834d6aaf8)

Thanks, should `.github/workflows/sanity_checks.yml` be updated then?

**Comment by neheb** [comment]
Yeah I think so. Separate PR probably.

**Pull request merged**
