### PR TITLE
add imgui-docking

### PR DESCRIPTION
**Pull request by tmayoff**
The commit history get really messed up with the last [PR](https://github.com/mesonbuild/wrapdb/pull/1227).

### CODE REVIEW

**Comment by benoit-pierre** [comment]
You could have rebased and force-pushed.

**Comment by tmayoff** [comment]
I tried a couple of times, but I'm not going to spend time messing with it. This was easier and faster

**Comment by tmayoff** [comment]
Thanks @benoit-pierre for the help. This should be good to merge, the failure is the same as the non-docking branch

**Comment by AstroOrbis** [comment]
If we could update this to 1.91.3 to match the `imgui` dependency or update both to use 1.91.5 and 1.91.5-docking respectively that'd be amazing, as using a local patch isn't always a viable/maintainable option. LGTM!

**Comment by tmayoff** [comment]
I'll bump the version once I get a chance closer to the weekend, otherwise someone else can do it before then now that this is merged

**Pull request merged**
