### PR TITLE
mpdecimal: fix compilation with clang-cl

### PR DESCRIPTION
**Pull request by neheb**
That ml thi causes a linking error

### CODE REVIEW

**Comment by neheb** [comment]
Oh windows compilation in general is broken. This will be fun.

**Comment by neheb** [comment]
https://developercommunity.visualstudio.com/t/no-symbol-udivti3-in-clang-rtbuiltins-x86-64lib/1510286 <-- sigh

**Comment by neheb** [comment]
```
ld.lld: error: unable to automatically import from _ZN7decimal7contextE with relocation type IMAGE_REL_AMD64_SECREL in subprojects/mpdecimal-2.5.1/libmpdec++/examples/factorial.exe.p/factorial.cc.obj
```

lolwut?

**Comment by neheb** [comment]
it can remain broken.

**Comment by skrah** [comment]
`clang-cl`, including a workaround for the above `clang-cl` issue, is supported in `mpdecimal 4.0.0`:

https://www.bytereef.org/mpdecimal/changelog.html

mpdecimal's own build scripts would use:

```
cd vcbuild
set CC=clang-cl
set CXX=clang-cl
vcbuild64.bat
```

**Pull request closed without merging**
