### PR TITLE
openblas-dll: create wrap

### PR DESCRIPTION
**Pull request by danielcjacobs**
Create new wrap for openblas-dll (windows only)

Version: 0.3.7 (will also add most recent version)

### CODE REVIEW

**Comment by danielcjacobs** [comment]
I know I didn't need to, but I merged mesondb master into my branch before creating the PR, and now it's acting as if I all the recent changes came from this PR...shouldn't it detect that the only differences between this PR and the current master is the openblass-dll changes?

**Comment by tp-m** [comment]
This looks like a binary wrap for a specific platform + architecture - is this something we want in wrapdb?

**Comment by jpakkane** [comment]
WrapDB is for source code only.

**Comment by danielcjacobs** [comment]
So I can't host this wrap here?

**Comment by xclaesse** [comment]
You can, but you would have to build from source instead of using prebuilt binaries. Upstream is using plain Makefile, you can "translate" them to meson.build. Maybe upstream could be interested to use a real build system instead of their hand crafted mess?

**Comment by xclaesse** [comment]
Sorry, they have cmake build system actually. You could try Meson's cmake module: https://mesonbuild.com/CMake-module.html.

**Pull request closed without merging**
