### PR TITLE
libtiff: fix build with MSVC

### PR DESCRIPTION
**Pull request by tp-m**
Would fail to link with

LINK : fatal error LNK1181: cannot open input file 'subprojects\tiff-4.1.0\libtiff\tiff4.lib'

because no symbols were exported.

### CODE REVIEW

**Comment by xclaesse** [comment]
You need to edit releases.json to add the release version.

**Comment by tp-m** [comment]
Ah, thanks!

I wonder whether that couldn't be checked as part of the sanity checks on the CI?

**Comment by tp-m** [comment]
Fixed, hopefully.

**Comment by xclaesse** [comment]
Thanks.

**Pull request merged**
